### ISSUE TITLE
oneacct gives ruby error

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1386]
---

Author Name: **Stefan Kooman** (Stefan Kooman)
Original Redmine Issue: 5455, https://dev.opennebula.org/issues/5455
Original Date: 2017-10-13
Original Assignee: Sergio Semedi

---

oneacct -u 0 --start 08/03/2017 --end 10/05/2017 --split

Showing active history records from 2017-03-08 00:00:00 +0100 to 2017-05-11 00:00:00 +0200

1. User 0                                                                        

 VID HOSTNAME        REAS     START_TIME       END_TIME MEMORY CPU
   7 redacted none 11/27 11:14:41              -   512M   1

 VID HOSTNAME        REAS     START_TIME       END_TIME MEMORY CPU NET_RX NET_TX
/usr/lib/one/ruby/cli/cli_helper.rb:301:in `block (2 levels) in data_array': undefined method `call' for nil:NilClass (NoMethodError)
Did you mean?  caller
        from /usr/lib/one/ruby/cli/cli_helper.rb:300:in `collect'
        from /usr/lib/one/ruby/cli/cli_helper.rb:300:in `block in data_array'
        from /usr/lib/one/ruby/cli/cli_helper.rb:299:in `collect'
        from /usr/lib/one/ruby/cli/cli_helper.rb:299:in `data_array'
        from /usr/lib/one/ruby/cli/cli_helper.rb:268:in `print_data'
        from /usr/lib/one/ruby/cli/cli_helper.rb:263:in `print_table'
        from /usr/lib/one/ruby/cli/cli_helper.rb:229:in `show'
        from /usr/bin/oneacct:143:in `block (4 levels) in <main>'
        from /usr/bin/oneacct:141:in `each'
        from /usr/bin/oneacct:141:in `block (3 levels) in <main>'
        from /usr/bin/oneacct:136:in `each'
        from /usr/bin/oneacct:136:in `block (2 levels) in <main>'
        from /usr/lib/one/ruby/cli/command_parser.rb:449:in `run'
        from /usr/lib/one/ruby/cli/command_parser.rb:76:in `initialize'
        from /usr/bin/oneacct:35:in `new'
        from /usr/bin/oneacct:35:in `<main>'

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-10-13T08:44:52Z

---

I can reproduce this on ONE 5.4.0 (also ONE 5.2.1). Environment: Ubuntu Xenial 16.04

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Sergio Semedi** (Sergio Semedi)
Original Date: 2017-10-18T12:58:39Z

---

Stefan Kooman wrote:
> I can reproduce this on ONE 5.4.0 (also ONE 5.2.1). Environment: Ubuntu Xenial 16.04

Hi,

Im afraid that im not able to reproduce this issue on my opennebula installation.
would you care to post here the result of: $ oneacct -x -u 0 --start 08/03/2017 --end 10/05/2017 --split

Send me the output via email (ssemedi@opennebula.org) if u prefer to share it privately.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Ruben S. Montero** (@rsmontero)
Original Date: 2017-10-27T09:49:57Z

---

If the error persists we can reopen the ticket

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Stefan Kooman** (Stefan Kooman)
Original Date: 2017-10-27T12:02:19Z

---

-x (xml) and -j (json) output works fine. So it's something having trouble parsing the output it gets.

**Comment by OpenNebulaProject** [comment]
---

Original Redmine Comment
Author Name: **Sergio Semedi** (Sergio Semedi)
Original Date: 2017-10-27T17:23:47Z

---

Yes but the problem is that the command works perfectly for me so it would be nice if u could share your output, after that we will track any clue to reproduce the problem and find the solution.
