### ISSUE TITLE
sunstone: rbvmomi/type_loader.rb:16:in `load': undefined method `getbyte'

### ISSUE THREAD

**Issue by himbeere** [OpenNebula/one#1633]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [X] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
Sunstone is not starting anymore. Error message:

```
/usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/type_loader.rb:16:in `load': undefined method `getbyte' for false:FalseClass (NoMethodError)
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/type_loader.rb:16:in `block in initialize'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/type_loader.rb:16:in `open'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/type_loader.rb:16:in `initialize'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/connection.rb:265:in `new'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/connection.rb:265:in `load_vmodl'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/vim.rb:146:in `<class:VIM>'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/vim.rb:15:in `<module:RbVmomi>'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi/vim.rb:11:in `<top (required)>'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/one/ruby/vendors/rbvmomi/lib/rbvmomi.rb:12:in `<top (required)>'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/one/ruby/vcenter_driver.rb:41:in `<top (required)>'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/one/sunstone/routes/vcenter.rb:28:in `<top (required)>'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/one/sunstone/sunstone-server.rb:442:in `block in <main>'
        from /usr/lib/one/sunstone/sunstone-server.rb:441:in `each'
        from /usr/lib/one/sunstone/sunstone-server.rb:441:in `<main>'
```

### Expected Behavior
Sunstone should start.

### Actual Behavior
Sunstone crashes

**Comment by himbeere** [comment]
I must have messed up my ruby installation. After un-installation and re-installation of ruby and all gems sunstone works again. Sorry for the noise.
