### ISSUE TITLE
Oned segfaults during the start on Ubuntu 18.04

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#2013]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [x] Core
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

On Ubuntu 18.04 (only) the `oned` fails to start and segfaults after ~15 seconds:

```
Thread 17 "oned" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc97fa700 (LWP 27496)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055555562f74c in PoolSQL::list (this=0x555555b642d0, 
    oids=std::vector of length 0, capacity 0, 
    table=0x555555802785 "datastore_pool") at include/PoolSQL.h:117
#2  0x00005555556c553b in DatastorePool::list (this=0x555555b642d0, 
    oids=std::vector of length 0, capacity 0) at include/DatastorePool.h:151
#3  0x00005555556c4c38 in ImageManager::timer_action (this=0x555555b6aab0, 
    ar=...) at src/image/ImageManager.cc:151
#4  0x00005555557510ba in ActionListener::_do_action (this=0x555555b6ace0, 
    ar=...) at include/ActionManager.h:109
#5  0x0000555555750fc7 in ActionManager::loop (this=0x555555b6ad10, 
    _tout=..., trequest=...) at src/common/ActionManager.cc:112
#6  0x00005555555c6e44 in ActionManager::loop (this=0x555555b6ad10, 
    timeout=15) at include/ActionManager.h:180
#7  0x00005555556c4619 in image_action_loop (arg=0x555555b6aab0)
    at src/image/ImageManager.cc:39
#8  0x00007ffff61436db in start_thread (arg=0x7fffc97fa700)
    at pthread_create.c:463
#9  0x00007ffff58c688f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Last log entries:

```
Mon Apr 23 10:35:12 2018 [Z0][VMM][I]: 	Loading driver: kvm (KVM)
Mon Apr 23 10:35:12 2018 [Z0][VMM][E]: Wrong action: snap-create
Mon Apr 23 10:35:12 2018 [Z0][VMM][E]: Wrong action: snap-delete
Mon Apr 23 10:35:12 2018 [Z0][MAD][E]: MAD did not answer INIT command
Mon Apr 23 10:35:12 2018 [Z0][ONE][E]: Could not load driver
```

and, the deamon fails later:

```
Apr 23 10:35:25 ubuntu1804-func-50e68-0 kernel: [25960.779611] oned[28702]: segfault at 0 ip 0000000000000000 sp 00007f79577fdbe8 error 14 in oned[5579b4528000+36f000]
```

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
Pls check the updated description: https://github.com/OpenNebula/one/issues/2013#issue-316754856
