### ISSUE TITLE
oned can segfault after successfully allocating a new virtual network

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#2985]
**Vulnerability Details**
Sometimes calling `one.vn.reserve` method causes segfault.

**To Reproduce**
Choose any network with free IP

```bash
NETWORK_ID=0 # any existing network id
REQUEST="$(cat <<EOT
<?xml version="1.0"?> 
<methodCall>
    <methodName>one.vn.reserve</methodName>
    <params>
        <param><value>$(cat /var/lib/one/.one/one_auth)</value></param>
        <param><value><i4>$NETWORK_ID</i4></value></param>
        <param><value><string>SIZE="10000" NAME="test-netwok-$[RANDOM%100000]"</string></value></param>
    </params>
</methodCall>
EOT
)"

for i in $(seq 1 100); do
  curl -sS -k "${ONE_XMLRPC:-http://localhost:2633/RPC2}" --data "$REQUEST" || break
done
```

after few more attempts, oned dies with segfault:
```
[5725434.956988] oned[18051]: segfault at 1c0 ip 00007ffff5ed62b0 sp 00007ffff7fd1768 error 4 in libstdc++.so.6.0.25[7ffff5db1000+179000]
```
stack trace using `gdb`:
```
<F28>#0  0x00007ffff61e0970 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000057f578 in VirtualNetworkPool::set_vlan_id (this=0xb4ce50, vn=0x0) at src/vnm/VirtualNetworkPool.cc:409
#2  0x000000000057e2fb in VirtualNetworkPool::allocate (this=0xb4ce50, uid=0, gid=0, uname="oneadmin", gname="oneadmin", umask=127, pvid=0, vn_template=0x7fff986a2460, oid=0x7ffff7f4e918, cluster_ids=std::set with 2 elements = {...}, 
    error_str="") at src/vnm/VirtualNetworkPool.cc:154
#3  0x00000000004b9964 in VirtualNetworkReserve::request_execute (this=0xb678e0, paramList=..., att=...) at src/rm/RequestManagerVirtualNetwork.cc:375
#4  0x00000000004e8f77 in Request::execute (this=0xb678e0, _paramList=..., _callInfoP=0x7ffff7f4f660, _retval=0x7ffff7f4f400) at src/rm/Request.cc:422
#5  0x0000000000649263 in xmlrpc_c::c_executeMethod (envP=0x7ffff7f4f520, paramArrayP=0x7fff98758520, methodPtr=0xb678e0, callInfoPtr=0x7ffff7f4f660) at registry.cpp:281
#6  0x000000000064d0e9 in callNamedMethod (resultPP=0x7ffff7f4f550, callInfoP=0x7ffff7f4f660, paramArrayP=0x7fff98758520, methodP=<optimized out>, envP=0x7ffff7f4f520) at registry.c:307
#7  xmlrpc_dispatchCall (envP=envP@entry=0x7ffff7f4f520, registryP=registryP@entry=0xb631f0, methodName=0x7fff984ad790 "one.vn.reserve", paramArrayP=0x7fff98758520, callInfoP=callInfoP@entry=0x7ffff7f4f660, 
    resultPP=resultPP@entry=0x7ffff7f4f550) at registry.c:337
#8  0x000000000064d22c in xmlrpc_registry_process_call2 (envP=0x7ffff7f4f5e0, registryP=0xb631f0, 
    callXml=0x7fff987081f0 "<?xml version=\"1.0\"?> \n<methodCall>\n    <methodName>one.vn.reserve</methodName>\n    <params>\n        <param><value>oneadmin:redacted</value></param>\n        <param><value><i4>0</i4></value"..., callXmlLen=330, callInfo=0x7ffff7f4f660, responseXmlPP=0x7ffff7f4f5d8) at registry.c:426
#9  0x0000000000649db3 in xmlrpc_c::registry::processCall (this=0xb62c98, 
    callXml="<?xml version=\"1.0\"?> \n<methodCall>\n    <methodName>one.vn.reserve</methodName>\n    <params>\n        <param><value>oneadmin:redacted</value></param>\n        <param><value><i4>0</i4></value"..., 
    callInfoP=0x7ffff7f4f660, responseXmlP=0x7ffff7f4f710) at registry.cpp:524
#10 0x0000000000647bbd in xmlrpc_c::serverAbyss_impl::processCall (this=0x7fffbc0009c0, 
    call="<?xml version=\"1.0\"?> \n<methodCall>\n    <methodName>one.vn.reserve</methodName>\n    <params>\n        <param><value>oneadmin:redacted</value></param>\n        <param><value><i4>0</i4></value"..., 
    abyssSessionP=0x7ffff7f4f860, responseP=0x7ffff7f4f710) at server_abyss.cpp:789
#11 0x0000000000646d4c in xmlrpc_c::processXmlrpcCall (envP=0x7ffff7f4f7c0, arg=0x7fffbc0009c0, 
    callXml=0x7fff984354a0 "<?xml version=\"1.0\"?> \n<methodCall>\n    <methodName>one.vn.reserve</methodName>\n    <params>\n        <param><value>oneadmin:redacted</value></param>\n        <param><value><i4>0</i4></value"..., callXmlLen=330, abyssSessionP=0x7ffff7f4f860, responseXmlPP=0x7ffff7f4f7b8) at server_abyss.cpp:381
#12 0x000000000064c82c in processCall (trace=<optimized out>, accessControl=..., wantChunk=false, xmlProcessorArg=0x7fffbc0009c0, 
    xmlProcessor=0x646c9d <xmlrpc_c::processXmlrpcCall(xmlrpc_env*, void*, char const*, size_t, TSession*, xmlrpc_mem_block**)>, contentSize=<optimized out>, abyssSessionP=0x7ffff7f4f860) at abyss_handler.c:392
#13 handleXmlRpcCallReq (requestInfoP=<optimized out>, accessControl=..., wantChunk=<optimized out>, xmlProcessorArg=0x7fffbc0009c0, 
    xmlProcessor=0x646c9d <xmlrpc_c::processXmlrpcCall(xmlrpc_env*, void*, char const*, size_t, TSession*, xmlrpc_mem_block**)>, abyssSessionP=0x7ffff7f4f860) at abyss_handler.c:509
#14 xmlrpc_handleIfXmlrpcReq (handlerArg=<optimized out>, abyssSessionP=0x7ffff7f4f860, handledP=<optimized out>) at abyss_handler.c:573
#15 0x00000000006545e0 in runUserHandler (srvP=0x7fffbc000a60, sessionP=0x7ffff7f4f860) at server.c:631
#16 processRequestFromClient (connectionP=connectionP@entry=0x7fffbc000d70, lastReqOnConn=lastReqOnConn@entry=false, timeout=<optimized out>, keepAliveP=keepAliveP@entry=0x7ffff7f4f9ac) at server.c:724
#17 0x000000000065484d in serverFunc (userHandle=0x7fffbc000d70) at server.c:796
#18 0x0000000000659da7 in connJob (userHandle=0x7fffbc000d70) at conn.c:39
#19 0x0000000000659627 in execute (arg=0x7fffbc001de0) at thread_pthread.c:59
#20 0x00007ffff644a6ba in start_thread (arg=0x7ffff7f50400) at pthread_create.c:333
#21 0x00007ffff58df41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Expected behavior**
Don't die. Handle all the errors.

**Details**
 - Affected Component: Core
 - Hypervisor: KVM
 - Version: 5.6.1 (tested on xenial and bionic)

**Additional context**

Finaly, after restart, this reservation network will be created with 0 leases, but during removing it is showing an error and disappears:
```
[one.vn.delete] Cannot delete virtual network. Network ID is not part of the cluster set.
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Problem occurs only with Percona Xtradb Cluster

sqlite and mysql with tokudb engine is wotking without this problem

**Comment by rsmontero** [comment]
It may be an issue with Percona Xtradb Cluster, but oned should behave nicer. Thanks for the backtrace, we have identified the corner case that may lead to this. (It is actually assuming a DB behavior that is not follow by Percona, go figure...) We are fixing it.

BTW, I've updated the subject of the issue to better describe the issue.

Thanks.
