### ISSUE TITLE
Unable to upgrade database from 4.8 to 5.4 or 5.6

### ISSUE THREAD

**Issue by baby-gnu** [OpenNebula/one#3051]
**Description**
During an upgrade of a old 4.8 OpenNebula, I got the following error

```
onedb upgrade -s /var/lib/one/one.db
Sqlite database backup stored in /var/lib/one/one.db_2019-3-8_15:13:35.bck
Use 'onedb restore' to restore the DB.

>>> Running migrators for shared tables
Database migrated from 4.6.0 to 5.4.1 (OpenNebula 5.4.1) by onedb command.

>>> Running migrators for local tables
**************************************************************
*  WARNING  WARNING WARNING WARNING WARNING WARNING WARNING  *
**************************************************************

OpenNebula 4.13.80 improves the management of FAILED VMs  
Please remove (onevm delete) any FAILED VM before continuing. 

**************************************************************
*  WARNING  WARNING WARNING WARNING WARNING WARNING WARNING  *
**************************************************************


The scheduler (and oned) has been update to enforce access    
rights on system datastores. This new version also checks that
the user can access the System DS.
This *may require* to update system DS rights of your cloud

Do you want to proceed ? [y/N]y

SQLite3::ConstraintException: UNIQUE constraint failed: history.vid, history.seq
/usr/lib/ruby/vendor_ruby/sqlite3/statement.rb:108:in `step'
/usr/lib/ruby/vendor_ruby/sqlite3/statement.rb:108:in `block in each'
/usr/lib/ruby/vendor_ruby/sqlite3/statement.rb:107:in `loop'
/usr/lib/ruby/vendor_ruby/sqlite3/statement.rb:107:in `each'
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:158:in `to_a'
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:158:in `block in execute'
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:95:in `prepare'
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:134:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:189:in `block (2 levels) in _execute'
/usr/lib/ruby/vendor_ruby/sequel/database/logging.rb:35:in `log_yield'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:189:in `block in _execute'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `block in synchronize'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:101:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:180:in `_execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:151:in `execute_insert'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:968:in `execute_insert'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:338:in `insert'
/usr/lib/one/ruby/onedb/local/4.11.80_to_4.13.80.rb:145:in `block (2 levels) in up'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:141:in `block in each'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:337:in `block (2 levels) in fetch_rows'
/usr/lib/ruby/vendor_ruby/sqlite3/resultset.rb:138:in `each'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:328:in `block in fetch_rows'
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:269:in `query'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:187:in `block (2 levels) in _execute'
/usr/lib/ruby/vendor_ruby/sequel/database/logging.rb:35:in `log_yield'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:187:in `block in _execute'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `block in synchronize'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:101:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:180:in `_execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:130:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:952:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/sqlite.rb:322:in `fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:141:in `each'
/usr/lib/ruby/vendor_ruby/sequel/database/dataset.rb:48:in `fetch'
/usr/lib/one/ruby/onedb/local/4.11.80_to_4.13.80.rb:137:in `block in up'
/usr/lib/ruby/vendor_ruby/sequel/database/transactions.rb:136:in `_transaction'
/usr/lib/ruby/vendor_ruby/sequel/database/transactions.rb:110:in `block in transaction'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `block in synchronize'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:105:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/database/transactions.rb:99:in `transaction'
/usr/lib/one/ruby/onedb/local/4.11.80_to_4.13.80.rb:135:in `up'
/usr/lib/one/ruby/onedb/onedb.rb:232:in `apply_migrators'
/usr/lib/one/ruby/onedb/onedb.rb:179:in `upgrade'
/usr/bin/onedb:381:in `block (2 levels) in <main>'
/usr/lib/one/ruby/cli/command_parser.rb:449:in `run'
/usr/lib/one/ruby/cli/command_parser.rb:76:in `initialize'
/usr/bin/onedb:286:in `new'
/usr/bin/onedb:286:in `<main>'


The database will be restored
Sqlite database backup restored in /var/lib/one/one.db
```

**To Reproduce**
I managed to reproduce my problem on a lab environment, here is the 4.8 database

[onedb.sql](https://github.com/OpenNebula/one/files/2946472/onedb.txt)

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler or Storage]
 - Hypervisor: KVM
 - Version: 5.4.1 and 5.6.1

**Additional context**
Looking at the migrators I saw that the `4.11.80_to_4.13.80` does a strange thing to the `history` table:

1. rename it to `old_history` to process the entries after
2. create a new `history` table
3. insert all element of `old_history` with `etime` different from `0`
4. iterate over **all** elements of `old_history` to insert them to the new `history`

The problem comes from either **3** or **4**:

* do not insert all elements from `old_history` with `etime` different from `0`
* select **only** elements of `old_history` with `etime` equal `0` (see comment on line **136**)

https://github.com/OpenNebula/one/blob/release-5.6.1/src/onedb/local/4.11.80_to_4.13.80.rb#L128

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
I have used the database provided in the ticket and I was able to run the upgrade process. I have checked it for versions 5.6.0 and 5.11.80 (which is the current master one)

Since in 5.2 there was a change introduced to avoid using some "patch", maybe you can try this [commit](https://github.com/OpenNebula/one/commit/56c364d93fb9629fcf33fac4a721de7db34d498a) and maybe it fixes your problem.

Closing it, reopen if the problem still exists.
