### ISSUE TITLE
Unable to upgrade database from 5.6 to 5.8

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3176]
**Description**
It seems, that something wrong with the migration script, or I have specific case.

During run `onedb upgrade`, I've get the following error:
```
Mysql2::Error: Incorrect string value: '\xC4\x9B\xC5\xA1\xC4\x8D...' for column `opennebula`.`vm_pool`.`short_body` at row 1
/usr/lib/ruby/vendor_ruby/mysql2/client.rb:120:in `_query'
/usr/lib/ruby/vendor_ruby/mysql2/client.rb:120:in `block in query'
/usr/lib/ruby/vendor_ruby/mysql2/client.rb:119:in `handle_interrupt'
/usr/lib/ruby/vendor_ruby/mysql2/client.rb:119:in `query'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:137:in `block in _execute'
/usr/lib/ruby/vendor_ruby/sequel/database/logging.rb:38:in `log_connection_yield'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:132:in `_execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/utils/mysql_mysql2.rb:38:in `block in execute'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:87:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:269:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/adapters/utils/mysql_mysql2.rb:38:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:72:in `execute_insert'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:1101:in `execute_insert'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:398:in `insert'
/usr/lib/one/ruby/onedb/local/5.6.0_to_5.7.80.rb:207:in `block (2 levels) in feature_2489_2671'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:151:in `block in each'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:238:in `block (2 levels) in fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:238:in `each'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:238:in `block in fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:152:in `_execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/utils/mysql_mysql2.rb:38:in `block in execute'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:87:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:269:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/adapters/utils/mysql_mysql2.rb:38:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:1085:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:273:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:236:in `fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:151:in `each'
/usr/lib/ruby/vendor_ruby/sequel/database/dataset.rb:51:in `fetch'
/usr/lib/one/ruby/onedb/local/5.6.0_to_5.7.80.rb:199:in `block in feature_2489_2671'
/usr/lib/ruby/vendor_ruby/sequel/database/transactions.rb:204:in `_transaction'
/usr/lib/ruby/vendor_ruby/sequel/database/transactions.rb:179:in `block in transaction'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:91:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:269:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/database/transactions.rb:145:in `transaction'
/usr/lib/one/ruby/onedb/local/5.6.0_to_5.7.80.rb:198:in `feature_2489_2671'
/usr/lib/one/ruby/onedb/local/5.6.0_to_5.7.80.rb:43:in `up'
/usr/lib/one/ruby/onedb/onedb.rb:232:in `apply_migrators'
/usr/lib/one/ruby/onedb/onedb.rb:179:in `upgrade'
/usr/bin/onedb:389:in `block (2 levels) in <main>'
/usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
/usr/bin/onedb:294:in `new'
/usr/bin/onedb:294:in `<main>'
```
Any ideas, how to solve it?

**Details**
 - Affected Component: onedb
 - Hypervisor: KVM
 - Version: 5.8

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
I'm not sure but I think might be connected with the specific UTF symbols.

**Comment by kvaps** [comment]
Done, this is fix: https://github.com/OpenNebula/one/pull/3184

**Comment by rsmontero** [comment]
Thanks, we'll take a look at it!!! In the past we had several problems with the enconding affecting non-english users.

**Comment by kvaps** [comment]
take a look, maybe better to place it in `create_table` method:
https://github.com/OpenNebula/one/blob/431cba56a3fdc1141b6899349621010b5b8478a7/src/onedb/database_schema.rb#L152-L166

**Comment by rsmontero** [comment]
This seems to be a problem because a wrong change in the encoding introduced in 5.6. It should not be an issue in current OPenNebula versions
