### ISSUE TITLE
Provision cleanup failed

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3234]
**Description**

Cleanup of failed provision fails:

```
# oneprovision create --verbose packet2hosts.yaml
2019-04-15 13:37:53 INFO  : Creating provision objects
WARNING: This operation can take tens of minutes. Please be patient.
2019-04-15 13:37:53 INFO  : Deploying
2019-04-15 13:39:51 INFO  : Monitoring hosts
2019-04-15 13:39:59 INFO  : Checking working SSH connection
2019-04-15 13:40:01 INFO  : Configuring hosts
2019-04-15 13:44:33 WARN  : Command FAILED (code=2): ANSIBLE_CONFIG=/tmp/d20190415-23694-1nktxwh/ansible.cfg ansible-playbook --ssh-common-args='-o UserKnownHostsFile=/dev/null' -i /tmp/d20190415-23694-1nktxwh/inventory -i /usr/share/one/oneprovision/ansible/inventories/static_vxlan/ /usr/share/one/oneprovision/ansible/static_vxlan.yml
ERROR: Failed to configure hosts
...
original message: no test named 'in'
1. quit
2. retry
3. skip
4. cleanup
Choose failover method:
4 
/usr/lib/one/oneprovision/lib/provision.rb:67:in `delete': wrong number of arguments (0 for 2) (ArgumentError)
	from /usr/lib/one/oneprovision/lib/provision.rb:226:in `rescue in create'
	from /usr/lib/one/oneprovision/lib/provision.rb:172:in `create'
	from /usr/lib/one/ruby/cli/one_helper/oneprovision_helper.rb:85:in `create'
	from /usr/bin/oneprovision:210:in `block (2 levels) in <main>'
	from /usr/lib/one/ruby/cli/command_parser.rb:470:in `call'
	from /usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
	from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
	from /usr/bin/oneprovision:56:in `new'
	from /usr/bin/oneprovision:56:in `<main>'
```

(note: the problem here is not the failed Ansible, but failed failover cleanup after)

**Details**
 - Affected Component: Provision
 - Version: 5.8.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge:

OpenNebula/one: https://github.com/OpenNebula/one/pull/3238
OpenNebula/docs: https://github.com/OpenNebula/docs/pull/592
