### ISSUE TITLE
onedb fsck check fails on the vrouter

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3342]
**Description**
onedb fsck check fails on the vrouter

**To Reproduce**

I have two vrouters created, but not instantiated, this one causes an error during fsck:
```
NAME=dev-ip
NIC=[
  AR_ID="0",
  BRIDGE="vmbr0",
  FLOATING_IP="YES",
  NETWORK="int-ip",
  NETWORK_ID="2",
  NIC_ID="0",
  VROUTER_IP="10.28.36.80",
  VROUTER_MAC="02:00:0a:1c:24:50" ]
NIC=[
  AR_ID="0",
  FLOATING_IP="YES",
  NETWORK="dev-ip-gw",
  NETWORK_ID="137",
  NIC_ID="1",
  VROUTER_IP="172.16.0.1",
  VROUTER_MAC="02:00:ac:10:00:01" ]
TEMPLATE_ID="26"
```
 fsck is working fine when I remove it and until I create it again

**Expected behavior**
A c checkomplete fsck

**Details**
 - Affected Component: onedb
 - Hypervisor: KVM
 - Version: 5.8.1

**Additional context**
Trace log:

```
undefined method `empty?' for nil:NilClass
/usr/lib/one/ruby/onedb/fsck.rb:530:in `mac_s_to_i'
/usr/lib/one/ruby/onedb/fsck/vrouter.rb:56:in `block (2 levels) in check_vrouter'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:190:in `block in each'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:189:in `upto'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:189:in `each'
/usr/lib/one/ruby/onedb/fsck/vrouter.rb:11:in `block in check_vrouter'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:151:in `block in each'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:238:in `block (2 levels) in fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:238:in `each'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:238:in `block in fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:152:in `_execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/utils/mysql_mysql2.rb:38:in `block in execute'
/usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:91:in `hold'
/usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:269:in `synchronize'
/usr/lib/ruby/vendor_ruby/sequel/adapters/utils/mysql_mysql2.rb:38:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:1085:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:273:in `execute'
/usr/lib/ruby/vendor_ruby/sequel/adapters/mysql2.rb:236:in `fetch_rows'
/usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:151:in `each'
/usr/lib/ruby/vendor_ruby/sequel/database/dataset.rb:51:in `fetch'
/usr/lib/one/ruby/onedb/fsck/vrouter.rb:7:in `check_vrouter'
/usr/lib/one/ruby/onedb/fsck.rb:382:in `fsck'
/usr/lib/one/ruby/onedb/onedb.rb:280:in `fsck'
/usr/bin/onedb:405:in `block (2 levels) in <main>'
/usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
/usr/bin/onedb:294:in `new'
/usr/bin/onedb:294:in `<main>'
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
The bug was fixed here: https://github.com/OpenNebula/one/commit/b11c8a55660fc953219ef1baea558011807164f1
