### ISSUE TITLE
Build fails with 'npm ERR! Error: Invalid name: "@novnc/novnc'

### ISSUE THREAD

**Issue by dcarlojr** [OpenNebula/one#3590]
**Description**
When building OpenNebula 5.8.4 on RHEL 7.7 the build.sh script fails with this error:
```
what-input#2.0.1 bower_components/what-input
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "@novnc/novnc"
npm ERR!     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:266:40
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.0-1062.el7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/admcarlo/src/opennebula-5.8.4/src/sunstone/public/bower_components/no-vnc
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/admcarlo/src/opennebula-5.8.4/src/sunstone/public/bower_components/no-vnc/npm-debug.log
npm ERR! not ok code 0

```

**To Reproduce**
``` bash
git clone https://github.com/OpenNebula/one opennebula-5.8.4
cd opennebula-5.8.4/
git checkout tags/release-5.8.4
cd share/man
./build.sh
cd ../..
cd src/sunstone/public/
./build.sh -d
export PATH=$PATH:$PWD/node_modules/.bin
echo $PATH
./build.sh
```

**Expected behavior**
A successful build

**Details**
 - Affected Component: Sunstone / no-vnc?
 - Hypervisor: N/A
 - Versions: 
   - OpenNebula: 5.8.4
   - OS: RHEL 7.7
   - npm: ]1.4.21
   - node: v0.10.30
   - no-vnc: 1.1.0

**Additional context**
Code was cloned on 08/14/2019

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dcarlojr** [comment]
@dann1 Thanks for the link and sorry for the dup!

**Comment by jloboescalona2** [comment]
Go to the project and use this command sudo ./install.sh -u USER -g GROUP -l replace the USER and GROUP with your user, in case that otherwise you can pass me the complete log
