### ISSUE TITLE
Onedb fsck: undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4328]
**Description**
Hi!, I just faced with the next error during fsck after opennebula upgrade from 5.8.5 to 5.10.1
```
...
User 2680 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2681 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2681 quotas: Image 1407	RVMS has 1 	is	0
User 2681 quotas: Image 1903	RVMS has 0 	is	1
User 2682 quotas: VNet 23	LEASES_USED has 1 	is	0
User 2682 quotas: Image 1408	RVMS has 1 	is	0
User 2682 quotas: Image 1905	RVMS has 0 	is	1

undefined method `text' for nil:NilClass
/usr/lib/one/ruby/onedb/fsck/quotas.rb:497:in `block in calculate_vnet_quotas'
/usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:238:in `block in each'
/usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `upto'
/usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `each'
/usr/lib/one/ruby/onedb/fsck/quotas.rb:496:in `calculate_vnet_quotas'
/usr/lib/one/ruby/onedb/fsck/quotas.rb:77:in `calculate_quotas'
/usr/lib/one/ruby/onedb/fsck/quotas.rb:39:in `block (2 levels) in check_fix_quotas'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/dataset/actions.rb:152:in `block in each'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/mysql2.rb:238:in `block (2 levels) in fetch_rows'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/mysql2.rb:238:in `each'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/mysql2.rb:238:in `block in fetch_rows'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/mysql2.rb:151:in `_execute'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `block in execute'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `execute'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/dataset/actions.rb:1089:in `execute'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/mysql2.rb:276:in `execute'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/adapters/mysql2.rb:236:in `fetch_rows'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/dataset/actions.rb:152:in `each'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/database/dataset.rb:51:in `fetch'
/usr/lib/one/ruby/onedb/fsck/quotas.rb:26:in `block in check_fix_quotas'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/share/one/gems-dist/gems/sequel-5.25.0/lib/sequel/database/transactions.rb:199:in `transaction'
/usr/lib/one/ruby/onedb/fsck/quotas.rb:16:in `check_fix_quotas'
/usr/lib/one/ruby/onedb/fsck.rb:465:in `fsck'
/usr/lib/one/ruby/onedb/onedb.rb:281:in `fsck'
/usr/bin/onedb:435:in `block (2 levels) in <main>'
/usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
/usr/bin/onedb:324:in `new'
/usr/bin/onedb:324:in `<main>'

Error running fsck version 5.10.0
The database will be restored
mysql: [Warning] Using a password on the command line interface can be insecure.
MySQL DB opennebula at mysql restored.
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Fsck successfully finished

**Details**
 - Affected Component: onedb
 - Hypervisor: KVM
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @kvaps 

I'm trying to reproduce the bug, but I'm not able to. Could you please send me your database so I can debug the problem with that?

Thanks!
Álex.

**Comment by kvaps** [comment]
Got it, this object was cause this error:

```bash
# oneuser show 2684
USER 2684 INFORMATION                                                           
ID              : 2684                
NAME            : ov2501              
GROUP           : ov2501              
SECONDARY GROUPS: 1,2479,2709         
PASSWORD        : redacted
AUTH_DRIVER     : core                
ENABLED         : Yes                 

TOKENS                                                                          

USER TEMPLATE                                                                   
TOKEN_PASSWORD="redacted"

VMS USAGE & QUOTAS                                                              

              VMS               MEMORY                  CPU     SYSTEM_DISK_SIZE
      0 /       -        0M /        -      0.00 /        -        0M /        -

VMS USAGE & QUOTAS - RUNNING                                                    

      RUNNING VMS       RUNNING MEMORY          RUNNING CPU
      0 /       -        0M /        -      0.00 /        -

DATASTORE USAGE & QUOTAS                                                        

NETWORK USAGE & QUOTAS                                                          

          ID               LEASES
Traceback (most recent call last):
	22: from /usr/bin/oneuser:36:in `<main>'
	21: from /usr/bin/oneuser:36:in `new'
	20: from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
	19: from /usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
	18: from /usr/bin/oneuser:557:in `block (2 levels) in <main>'
	17: from /usr/lib/one/ruby/cli/one_helper.rb:804:in `show_resource'
	16: from /usr/lib/one/ruby/cli/one_helper/oneuser_helper.rb:605:in `format_resource'
	15: from /usr/lib/one/ruby/cli/one_helper/onequota_helper.rb:458:in `format_quota'
	14: from /usr/lib/one/ruby/cli/cli_helper.rb:256:in `show'
	13: from /usr/lib/one/ruby/cli/cli_helper.rb:298:in `print_table'
	12: from /usr/lib/one/ruby/cli/cli_helper.rb:303:in `print_data'
	11: from /usr/lib/one/ruby/cli/cli_helper.rb:334:in `data_array'
	10: from /usr/lib/one/ruby/cli/cli_helper.rb:334:in `collect'
	 9: from /usr/lib/one/ruby/cli/cli_helper.rb:335:in `block in data_array'
	 8: from /usr/lib/one/ruby/cli/cli_helper.rb:335:in `collect'
	 7: from /usr/lib/one/ruby/cli/cli_helper.rb:336:in `block (2 levels) in data_array'
	 6: from /usr/lib/one/ruby/cli/one_helper/onequota_helper.rb:448:in `block (2 levels) in format_quota'
	 5: from /usr/lib/one/ruby/cli/one_helper/onequota_helper.rb:496:in `get_default_limit'
	 4: from /usr/lib/one/ruby/opennebula/xml_element.rb:87:in `[]'
	 3: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:154:in `xpath'
	 2: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:179:in `xpath_internal'
	 1: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:198:in `xpath_impl'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:198:in `evaluate': ERROR: Invalid expression: NETWORK_QUOTA/NETWORK[ID=]/LEASES (Nokogiri::XML::XPath::SyntaxError)
```

```xml
<USER>
  <ID>2684</ID>
  <GID>2479</GID>
  <GROUPS>
    <ID>1</ID>
    <ID>2479</ID>
    <ID>2709</ID>
  </GROUPS>
  <GNAME>ov2501</GNAME>
  <NAME>ov2501</NAME>
  <PASSWORD><![CDATA[redacted]]></PASSWORD>
  <AUTH_DRIVER><![CDATA[core]]></AUTH_DRIVER>
  <ENABLED>1</ENABLED>
  <TEMPLATE>
    <TOKEN_PASSWORD><![CDATA[redacted]]></TOKEN_PASSWORD>
  </TEMPLATE>
  <DATASTORE_QUOTA/>
  <NETWORK_QUOTA>
    <NETWORK>
      <ID><![CDATA[23]]></ID>
      <LEASES><![CDATA[-1]]></LEASES>
      <LEASES_USED><![CDATA[0]]></LEASES_USED>
    </NETWORK>
    <NETWORK>
      <ID><![CDATA[6]]></ID>
      <LEASES><![CDATA[-1]]></LEASES>
      <LEASES_USED><![CDATA[1]]></LEASES_USED>
    </NETWORK>
    <NETWORK>
      <LEASES><![CDATA[-1]]></LEASES>
      <LEASES_USED><![CDATA[1]]></LEASES_USED>
    </NETWORK>
  </NETWORK_QUOTA>
  <VM_QUOTA/>
  <IMAGE_QUOTA>
    <IMAGE>
      <ID><![CDATA[1408]]></ID>
      <RVMS><![CDATA[-1]]></RVMS>
      <RVMS_USED><![CDATA[1]]></RVMS_USED>
    </IMAGE>
  </IMAGE_QUOTA>
  <DEFAULT_USER_QUOTAS>
    <DATASTORE_QUOTA>
      <DATASTORE>
        <ID><![CDATA[105]]></ID>
        <IMAGES><![CDATA[3]]></IMAGES>
        <IMAGES_USED><![CDATA[0]]></IMAGES_USED>
        <SIZE><![CDATA[10240]]></SIZE>
        <SIZE_USED><![CDATA[0]]></SIZE_USED>
      </DATASTORE>
      <DATASTORE>
        <ID><![CDATA[202]]></ID>
        <IMAGES><![CDATA[3]]></IMAGES>
        <IMAGES_USED><![CDATA[0]]></IMAGES_USED>
        <SIZE><![CDATA[10240]]></SIZE>
        <SIZE_USED><![CDATA[0]]></SIZE_USED>
      </DATASTORE>
    </DATASTORE_QUOTA>
    <NETWORK_QUOTA/>
    <VM_QUOTA/>
    <IMAGE_QUOTA/>
  </DEFAULT_USER_QUOTAS>
</USER>
```

**Comment by kvaps** [comment]
So one of the vnet leases for the user have no `ID`, I've just removed this LEASE from the mysql, and onedb fsck started working fine

**Comment by al3xhh** [comment]
Thank you for the information @kvaps I will work on the fix!

**Comment by kvaps** [comment]
Another object:

```bash
# onegroup show 2479
GROUP 2479 INFORMATION                                                          
ID             : 2479                
NAME           : ov2501              

GROUP TEMPLATE                                                                  
SUNSTONE=[
  DEFAULT_VIEW="vps",
  GROUP_ADMIN_DEFAULT_VIEW="vps",
  GROUP_ADMIN_VIEWS="vps",
  VIEWS="vps" ]

USER ID ADMIN
   2684

VMS USAGE & QUOTAS                                                              

              VMS               MEMORY                  CPU     SYSTEM_DISK_SIZE
      0 /       0        0M /       0M      0.00 /     0.00        0M /       0M

VMS USAGE & QUOTAS - RUNNING                                                    

      RUNNING VMS       RUNNING MEMORY          RUNNING CPU
     -1 /       -     -512M /        -     -0.33 /        -

DATASTORE USAGE & QUOTAS                                                        

NETWORK USAGE & QUOTAS                                                          

Traceback (most recent call last):
	21: from /usr/bin/onegroup:39:in `<main>'
	20: from /usr/bin/onegroup:39:in `new'
	19: from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
	18: from /usr/lib/one/ruby/cli/command_parser.rb:470:in `run'
	17: from /usr/bin/onegroup:169:in `block (2 levels) in <main>'
	16: from /usr/lib/one/ruby/cli/one_helper.rb:853:in `show_resource'
	15: from /usr/lib/one/ruby/cli/one_helper/onegroup_helper.rb:332:in `format_resource'
	14: from /usr/lib/one/ruby/cli/one_helper/onequota_helper.rb:458:in `format_quota'
	13: from /usr/lib/one/ruby/cli/cli_helper.rb:372:in `show'
	12: from /usr/lib/one/ruby/cli/cli_helper.rb:482:in `print_table'
	11: from /usr/lib/one/ruby/cli/cli_helper.rb:561:in `data_array'
	10: from /usr/lib/one/ruby/cli/cli_helper.rb:561:in `collect'
	 9: from /usr/lib/one/ruby/cli/cli_helper.rb:562:in `block in data_array'
	 8: from /usr/lib/one/ruby/cli/cli_helper.rb:562:in `collect'
	 7: from /usr/lib/one/ruby/cli/cli_helper.rb:563:in `block (2 levels) in data_array'
	 6: from /usr/lib/one/ruby/cli/one_helper/onequota_helper.rb:448:in `block (2 levels) in format_quota'
	 5: from /usr/lib/one/ruby/cli/one_helper/onequota_helper.rb:496:in `get_default_limit'
	 4: from /usr/lib/one/ruby/opennebula/xml_element.rb:87:in `[]'
	 3: from /usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/searchable.rb:154:in `xpath'
	 2: from /usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/searchable.rb:179:in `xpath_internal'
	 1: from /usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/searchable.rb:198:in `xpath_impl'
/usr/share/one/gems-dist/gems/nokogiri-1.10.5/lib/nokogiri/xml/searchable.rb:198:in `evaluate': ERROR: Invalid expression: NETWORK_QUOTA/NETWORK[ID=]/LEASES (Nokogiri::XML::XPath::SyntaxError)
```

```xml
# onegroup show 2479 -x
<GROUP>
  <ID>2479</ID>
  <NAME>ov2501</NAME>
  <TEMPLATE>
    <SUNSTONE>
      <DEFAULT_VIEW><![CDATA[vps]]></DEFAULT_VIEW>
      <GROUP_ADMIN_DEFAULT_VIEW><![CDATA[vps]]></GROUP_ADMIN_DEFAULT_VIEW>
      <GROUP_ADMIN_VIEWS><![CDATA[vps]]></GROUP_ADMIN_VIEWS>
      <VIEWS><![CDATA[vps]]></VIEWS>
    </SUNSTONE>
  </TEMPLATE>
  <USERS>
    <ID>2684</ID>
  </USERS>
  <ADMINS/>
  <DATASTORE_QUOTA/>
  <NETWORK_QUOTA>
    <NETWORK>
      <ID><![CDATA[23]]></ID>
      <LEASES><![CDATA[0]]></LEASES>
      <LEASES_USED><![CDATA[0]]></LEASES_USED>
    </NETWORK>
    <NETWORK>
      <ID><![CDATA[6]]></ID>
      <LEASES><![CDATA[-1]]></LEASES>
      <LEASES_USED><![CDATA[1]]></LEASES_USED>
    </NETWORK>
    <NETWORK>
      <LEASES><![CDATA[-1]]></LEASES>
      <LEASES_USED><![CDATA[1]]></LEASES_USED>
    </NETWORK>
  </NETWORK_QUOTA>
  <VM_QUOTA>
    <VM>
      <CPU><![CDATA[0]]></CPU>
      <CPU_USED><![CDATA[0]]></CPU_USED>
      <MEMORY><![CDATA[0]]></MEMORY>
      <MEMORY_USED><![CDATA[0]]></MEMORY_USED>
      <RUNNING_CPU><![CDATA[-1]]></RUNNING_CPU>
      <RUNNING_CPU_USED><![CDATA[-0.33]]></RUNNING_CPU_USED>
      <RUNNING_MEMORY><![CDATA[-1]]></RUNNING_MEMORY>
      <RUNNING_MEMORY_USED><![CDATA[-512]]></RUNNING_MEMORY_USED>
      <RUNNING_VMS><![CDATA[-1]]></RUNNING_VMS>
      <RUNNING_VMS_USED><![CDATA[-1]]></RUNNING_VMS_USED>
      <SYSTEM_DISK_SIZE><![CDATA[0]]></SYSTEM_DISK_SIZE>
      <SYSTEM_DISK_SIZE_USED><![CDATA[0]]></SYSTEM_DISK_SIZE_USED>
      <VMS><![CDATA[0]]></VMS>
      <VMS_USED><![CDATA[0]]></VMS_USED>
    </VM>
  </VM_QUOTA>
  <IMAGE_QUOTA>
    <IMAGE>
      <ID><![CDATA[1408]]></ID>
      <RVMS><![CDATA[-1]]></RVMS>
      <RVMS_USED><![CDATA[1]]></RVMS_USED>
    </IMAGE>
  </IMAGE_QUOTA>
  <DEFAULT_GROUP_QUOTAS>
    <DATASTORE_QUOTA>
      <DATASTORE>
        <ID><![CDATA[2]]></ID>
        <IMAGES><![CDATA[0]]></IMAGES>
        <IMAGES_USED><![CDATA[0]]></IMAGES_USED>
        <SIZE><![CDATA[0]]></SIZE>
        <SIZE_USED><![CDATA[0]]></SIZE_USED>
      </DATASTORE>
      <DATASTORE>
        <ID><![CDATA[100]]></ID>
        <IMAGES><![CDATA[0]]></IMAGES>
        <IMAGES_USED><![CDATA[0]]></IMAGES_USED>
        <SIZE><![CDATA[0]]></SIZE>
        <SIZE_USED><![CDATA[0]]></SIZE_USED>
      </DATASTORE>
      <DATASTORE>
        <ID><![CDATA[174]]></ID>
        <IMAGES><![CDATA[0]]></IMAGES>
        <IMAGES_USED><![CDATA[0]]></IMAGES_USED>
        <SIZE><![CDATA[0]]></SIZE>
        <SIZE_USED><![CDATA[0]]></SIZE_USED>
      </DATASTORE>
    </DATASTORE_QUOTA>
    <NETWORK_QUOTA>
      <NETWORK>
        <ID><![CDATA[23]]></ID>
        <LEASES><![CDATA[0]]></LEASES>
        <LEASES_USED><![CDATA[0]]></LEASES_USED>
      </NETWORK>
      <NETWORK>
        <ID><![CDATA[3]]></ID>
        <LEASES><![CDATA[0]]></LEASES>
        <LEASES_USED><![CDATA[0]]></LEASES_USED>
      </NETWORK>
    </NETWORK_QUOTA>
    <VM_QUOTA>
      <VM>
        <CPU><![CDATA[0]]></CPU>
        <CPU_USED><![CDATA[0]]></CPU_USED>
        <MEMORY><![CDATA[0]]></MEMORY>
        <MEMORY_USED><![CDATA[0]]></MEMORY_USED>
        <RUNNING_CPU><![CDATA[-2]]></RUNNING_CPU>
        <RUNNING_MEMORY><![CDATA[-2]]></RUNNING_MEMORY>
        <RUNNING_VMS><![CDATA[-2]]></RUNNING_VMS>
        <SYSTEM_DISK_SIZE><![CDATA[0]]></SYSTEM_DISK_SIZE>
        <SYSTEM_DISK_SIZE_USED><![CDATA[0]]></SYSTEM_DISK_SIZE_USED>
        <VMS><![CDATA[0]]></VMS>
        <VMS_USED><![CDATA[0]]></VMS_USED>
      </VM>
    </VM_QUOTA>
    <IMAGE_QUOTA/>
  </DEFAULT_GROUP_QUOTAS>
</GROUP>
```

**Comment by al3xhh** [comment]
PRs to merge in 5.10 and master:

- code: https://github.com/OpenNebula/one/pull/4339
- docs: https://github.com/OpenNebula/docs/pull/989

**Comment by kvaps** [comment]
I guess better to remove whole block:
```
<NETWORK><LEASES><![CDATA[-1]]></LEASES><LEASES_USED><![CDATA[1]]></LEASES_USED></NETWORK>
```
but current solution will avoid the problem
