### ISSUE TITLE
one_hm.rb crash

### ISSUE THREAD

**Issue by annttu** [OpenNebula/one#4507]
**Description**

one_hm.rb crashes and opennebula-hem sometimes stops executing hooks after that.
Also oned don't always start new one_hm.rb process after crash.

Error message
```
Tue Apr  7 14:12:13 2020 [Z0][HKM][E]: Hook driver crashed, recovering...
```

**To Reproduce**

This seems to be hard to reproduce manually, but happens regularly in production environment. It has happened more than 10 times. 

**Expected behavior**
Expecting opennebula-hem to keep executing hooks and one_hm.rb not to crash

**Details**
 - Affected Component: oned, hooks
 - Hypervisor: KVM
 - Version: 5.10.1

**Additional context**

We use external script to launch multiple virtual machines (+10) simultaneously.

We have hooks for LCM_INIT/DONE and LCM_INIT/PENDING states.
Sometimes issue resolves after restarting opennebula-hem service. If one_hm.rb is not alive after crash, issue resolves after restarting both opennebula and opennebula-hem service.

After crash onehem.log shows new events but no " Executing hook" or "Hook successfully executed for" messages.

strace output from one_hm.rb before crash

```
...
[pid  1007] write(1<pipe:[106150348]>, "\n", 1 <unfinished ...>
[pid  1008] <... futex resumed> )       = 0
[pid  1007] <... write resumed> )       = -1 EPIPE (Broken pipe)
[pid  1008] futex(0x555d6044c38c, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1007] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=989, si_uid=9869} ---
[pid  1007] futex(0x555d6044c38c, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid   989] futex(0x555d6044c38c, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1008] <... futex resumed> )       = 0
[pid   989] <... futex resumed> )       = 1
[pid  1008] futex(0x555d6044c330, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid   989] futex(0x555d6044c330, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1008] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid   989] <... futex resumed> )       = 0
[pid  1008] futex(0x555d6044c330, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid   989] futex(0x555d6044c388, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1008] <... futex resumed> )       = 0
[pid  1008] futex(0x555d6044c38c, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1007] <... futex resumed> )       = 0
[pid  1008] futex(0x555d60ab1748, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1007] futex(0x555d6044c330, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  1007] write(2</dev/null>, "#<Thread:0x0000555d60875df8@/usr/lib/one/mads/one_hm.rb:79 run> terminated with exception (report_on_exception is true):\n", 121) = 121
[pid  1007] ioctl(2</dev/null>, TCGETS, 0x7fa615d22a30) = -1 ENOTTY (Inappropriate ioctl for device)
[pid  1007] write(2</dev/null>, "/usr/lib/one/ruby/DriverExecHelper.rb:105:in `flush'", 52) = 52
[pid  1007] write(2</dev/null>, ": ", 2) = 2
[pid  1007] write(2</dev/null>, "Broken pipe", 11) = 11
[pid  1007] write(2</dev/null>, " (", 2) = 2
[pid  1007] write(2</dev/null>, "Errno::EPIPE", 12) = 12
[pid  1007] write(2</dev/null>, ")\n", 2) = 2
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/ruby/DriverExecHelper.rb:105:in `block in send_message'\n", 75) = 75
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/ruby/DriverExecHelper.rb:103:in `synchronize'\n", 65) = 65
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/ruby/DriverExecHelper.rb:103:in `send_message'\n", 66) = 66
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/mads/one_hm.rb:128:in `block in receiver_thread'\n", 68) = 68
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/mads/one_hm.rb:112:in `loop'\n", 48) = 48
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/mads/one_hm.rb:112:in `receiver_thread'\n", 59) = 59
[pid  1007] write(2</dev/null>, "\tfrom /usr/lib/one/mads/one_hm.rb:80:in `block in initialize'\n", 62) = 62
[pid  1007] futex(0x555d6044c388, FUTEX_WAKE_PRIVATE, 1) = 1
[pid   989] <... futex resumed> )       = 0
[pid   989] futex(0x555d6044c330, FUTEX_WAKE_PRIVATE, 1) = 0
[pid  1007] madvise(0x7fa615c23000, 1028096, MADV_DONTNEED <unfinished ...>
[pid   989] poll([{fd=63<anon_inode:[eventfd]>, events=POLLIN}], 1, 0 <unfinished ...>
[pid  1007] <... madvise resumed> )     = 0
[pid  1007] exit(0 <unfinished ...>
[pid   989] <... poll resumed> )        = 0 (Timeout)
[pid  1007] <... exit resumed>)
[pid  1007] +++ exited with 0 +++

...

[pid   989] <... futex resumed> )       = 0
[pid  1008] read(0<pipe:[106150347]>,  <unfinished ...>
[pid   989] futex(0x555d6044b138, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1008] <... read resumed> "FINALIZE\n", 8192) = 9
[pid   989] <... futex resumed> )       = 0

...

exit_group(0)                           = ?
+++ exited with 0 +++
```

one_hm.rb exits with status 0
pipe 1 is STDOUT

Ruby version ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu] from ubuntu 18.04 ruby package.

Oned uses 25000usec (0.025sec)  timeout while reading from mad STDOUT which might expire if ruby code is busy reading for example from another socket.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
Please, could you update to the latest version (5.10.4). You are probably being hit by this:
#4154
