### ISSUE TITLE
monitord has wrong default DATASTORE_LOCATION

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#4791]
**Description**
The monitoring is partially working. There is no VM disks monitoring data from the hosts.

**To Reproduce**
install and run opennebula with defaults (SYSTEM_DS with ssh TM_MAD) and a remote KVM host
instantiate a VM on a remote host
look for VM disks monitoring data

**Expected behavior**
The disks monitoring should be received and registered in OpenNebula

**Details**
 - Affected Component: [Monitord]
 - Hypervisor: [KVM]
 - Version: [development]

**Additional context**

Note the _DATASTORE_LOCATION_ (monitord.log with debug=5):
```
Fri May 22 08:50:18 2020 [Z0][MON][I]: Init Monitor Log system
Fri May 22 08:50:18 2020 [Z0][MON][I]: Starting Monitor Daemon
----------------------------------------
       Monitor Configuration File       
----------------------------------------
DATASTORE_LOCATION=oned.conf/datastores
DB=CONNECTIONS=15
HOST_MONITORING_EXPIRATION_TIME=43200
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 kvm,EXECUTABLE=one_im_ssh,NAME=kvm,SUNSTONE_NAME=KVM,THREADS=0
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 lxd,EXECUTABLE=one_im_ssh,NAME=lxd,SUNSTONE_NAME=LXD,THREADS=0
IM_MAD=ARGUMENTS=-r 3 -t 15 -w 90 firecracker,EXECUTABLE=one_im_ssh,NAME=firecracker,SUNSTONE_NAME=Firecracker,THREADS=0
IM_MAD=ARGUMENTS=-c -t 15 -r 0 vcenter,EXECUTABLE=one_im_sh,NAME=vcenter,SUNSTONE_NAME=VMWare vCenter
LOG=DEBUG_LEVEL=5,SYSTEM=FILE
MANAGER_TIMER=15
MONITORING_INTERVAL_HOST=180
NETWORK=ADDRESS=0.0.0.0,MONITOR_ADDRESS=10.2.14.43,PORT=4124,PRIKEY=,PUBKEY=,THREADS=8
PROBES_PERIOD=BEACON_HOST=30,MONITOR_HOST=120,MONITOR_VM=30,STATE_VM=30,SYNC_STATE_VM=180,SYSTEM_HOST=600
VM_MONITORING_EXPIRATION_TIME=43200
----------------------------------------
...
Fri May 22 08:35:21 2020 [Z0][MDP][D]: Received beacon for host 0: 1590125721
Fri May 22 08:35:25 2020 [Z0][MDP][D]: Received beacon for host 1: 1590125725
Fri May 22 08:35:32 2020 [Z0][MDP][D]: Received MONITOR_VM msg: Error executing monitor_ds_vm.rb: /var/tmp/one/im/kvm.d/../kvm-probes.d/vm/monitor/monitor_ds_vm.rb:39:in `chdir': No such file or directory - oned.conf/datastores (Errno::ENOENT)
	from /var/tmp/one/im/kvm.d/../kvm-probes.d/vm/monitor/monitor_ds_vm.rb:39:in `<main>'
Fri May 22 08:35:32 2020 [Z0][MDP][E]: Error executing monitor_ds_vm.rb: /var/tmp/one/im/kvm.d/../kvm-probes.d/vm/monitor/monitor_ds_vm.rb:39:in `chdir': No such file or directory - oned.conf/datastores (Errno::ENOENT)
	from /var/tmp/one/im/kvm.d/../kvm-probes.d/vm/monitor/monitor_ds_vm.rb:39:in `<main>'
Fri May 22 08:35:32 2020 [Z0][MDP][E]: Error parsing VM monitoring template: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 0, columns 7:16
Fri May 22 08:35:36 2020 [Z0][MON][I]: All monitor drivers finalized, exiting
...
```

Can't figure out how in this case the variable _var_location_ become 'oned.conf', though.

A workaround is to define DATASTORE_LOCATION in 'oned.conf'...

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment]
Fixed by commit https://github.com/OpenNebula/one/commit/2f614c64f33623efd2e2360a91d9a6be05f2f812
