### ISSUE TITLE
Ruby components fail to run if multiple rubygems modules installed

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4929]
**Description**
When multiple RubyGems modules are installed (one part of the distribution, other ones installed manually via `gem`), the run of commands / services can fail on module version conflict after custom paths are removed by #4304. Workaround is to uninstall non-distribution `rubygems` module.

```
$ onedb upgrade
/usr/share/rubygems/rubygems.rb:11: warning: already initialized constant Gem::VERSION
/usr/local/share/ruby/site_ruby/rubygems.rb:13: warning: previous definition of VERSION was here
/usr/share/rubygems/rubygems/compatibility.rb:13: warning: already initialized constant Gem::GEM_PRELUDE_SUCKAGE
/usr/local/share/ruby/site_ruby/rubygems/compatibility.rb:14: warning: previous definition of GEM_PRELUDE_SUCKAGE was here
/usr/share/rubygems/rubygems/compatibility.rb:34: warning: already initialized constant Gem::RubyGemsVersion
/usr/local/share/ruby/site_ruby/rubygems/compatibility.rb:34: warning: previous definition of RubyGemsVersion was here
/usr/share/rubygems/rubygems/compatibility.rb:36: warning: already initialized constant Gem::RbConfigPriorities
/usr/local/share/ruby/site_ruby/rubygems/compatibility.rb:38: warning: previous definition of RbConfigPriorities was here
/usr/share/rubygems/rubygems/compatibility.rb:54: warning: already initialized constant Gem::RubyGemsPackageVersion
/usr/local/share/ruby/site_ruby/rubygems/compatibility.rb:59: warning: previous definition of RubyGemsPackageVersion was here
/usr/share/rubygems/rubygems/defaults.rb:2: warning: already initialized constant Gem::DEFAULT_HOST
/usr/local/share/ruby/site_ruby/rubygems/defaults.rb:3: warning: previous definition of DEFAULT_HOST was here
/usr/share/rubygems/rubygems.rb:115: warning: already initialized constant Gem::RUBYGEMS_DIR
/usr/local/share/ruby/site_ruby/rubygems.rb:118: warning: previous definition of RUBYGEMS_DIR was here
/usr/share/rubygems/rubygems.rb:120: warning: already initialized constant Gem::WIN_PATTERNS
/usr/local/share/ruby/site_ruby/rubygems.rb:123: warning: previous definition of WIN_PATTERNS was here
/usr/share/rubygems/rubygems.rb:129: warning: already initialized constant Gem::GEM_DEP_FILES
/usr/local/share/ruby/site_ruby/rubygems.rb:132: warning: previous definition of GEM_DEP_FILES was here
/usr/share/rubygems/rubygems.rb:138: warning: already initialized constant Gem::REPOSITORY_SUBDIRECTORIES
/usr/local/share/ruby/site_ruby/rubygems.rb:142: warning: previous definition of REPOSITORY_SUBDIRECTORIES was here
/usr/share/rubygems/rubygems.rb:1060: warning: already initialized constant Gem::MARSHAL_SPEC_DIR
/usr/local/share/ruby/site_ruby/rubygems.rb:1355: warning: previous definition of MARSHAL_SPEC_DIR was here
/usr/share/rubygems/rubygems/version.rb:150: warning: already initialized constant Gem::Version::VERSION_PATTERN
/usr/local/share/ruby/site_ruby/rubygems/version.rb:157: warning: previous definition of VERSION_PATTERN was here
/usr/share/rubygems/rubygems/version.rb:151: warning: already initialized constant Gem::Version::ANCHORED_VERSION_PATTERN
/usr/local/share/ruby/site_ruby/rubygems/version.rb:158: warning: previous definition of ANCHORED_VERSION_PATTERN was here
/usr/share/rubygems/rubygems/requirement.rb:19: warning: already initialized constant Gem::Requirement::OPS
/usr/local/share/ruby/site_ruby/rubygems/requirement.rb:17: warning: previous definition of OPS was here
/usr/share/rubygems/rubygems/requirement.rb:30: warning: already initialized constant Gem::Requirement::PATTERN_RAW
/usr/local/share/ruby/site_ruby/rubygems/requirement.rb:30: warning: previous definition of PATTERN_RAW was here
/usr/share/rubygems/rubygems/requirement.rb:31: warning: already initialized constant Gem::Requirement::PATTERN
/usr/local/share/ruby/site_ruby/rubygems/requirement.rb:35: warning: previous definition of PATTERN was here
/usr/share/rubygems/rubygems/requirement.rb:33: warning: already initialized constant Gem::Requirement::DefaultRequirement
/usr/local/share/ruby/site_ruby/rubygems/requirement.rb:40: warning: previous definition of DefaultRequirement was here
/usr/share/rubygems/rubygems/requirement.rb:241: warning: already initialized constant Gem::Version::Requirement
/usr/local/share/ruby/site_ruby/rubygems/requirement.rb:288: warning: previous definition of Requirement was here
/usr/share/rubygems/rubygems/platform.rb:181: warning: already initialized constant Gem::Platform::RUBY
/usr/local/share/ruby/site_ruby/rubygems/platform.rb:198: warning: previous definition of RUBY was here
/usr/share/rubygems/rubygems/platform.rb:187: warning: already initialized constant Gem::Platform::CURRENT
/usr/local/share/ruby/site_ruby/rubygems/platform.rb:204: warning: previous definition of CURRENT was here
/usr/share/rubygems/rubygems/specification.rb:59: warning: already initialized constant Gem::Specification::NONEXISTENT_SPECIFICATION_VERSION
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:51: warning: previous definition of NONEXISTENT_SPECIFICATION_VERSION was here
/usr/share/rubygems/rubygems/specification.rb:82: warning: already initialized constant Gem::Specification::CURRENT_SPECIFICATION_VERSION
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:74: warning: previous definition of CURRENT_SPECIFICATION_VERSION was here
/usr/share/rubygems/rubygems/specification.rb:88: warning: already initialized constant Gem::Specification::SPECIFICATION_VERSION_HISTORY
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:80: warning: previous definition of SPECIFICATION_VERSION_HISTORY was here
/usr/share/rubygems/rubygems/specification.rb:106: warning: already initialized constant Gem::Specification::MARSHAL_FIELDS
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:98: warning: previous definition of MARSHAL_FIELDS was here
/usr/share/rubygems/rubygems/specification.rb:109: warning: already initialized constant Gem::Specification::TODAY
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:107: warning: previous definition of TODAY was here
/usr/share/rubygems/rubygems/specification.rb:111: warning: already initialized constant Gem::Specification::VALID_NAME_PATTERN
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:113: warning: previous definition of VALID_NAME_PATTERN was here
/usr/share/rubygems/rubygems/specification.rb:1419: warning: already initialized constant Gem::Specification::DateTimeFormat
/usr/local/share/ruby/site_ruby/rubygems/specification.rb:1761: warning: previous definition of DateTimeFormat was here
/usr/local/share/ruby/site_ruby/rubygems/path_support.rb:25:in `initialize': wrong number of arguments (0 for 1) (ArgumentError)
	from /usr/share/rubygems/rubygems.rb:357:in `new'
	from /usr/share/rubygems/rubygems.rb:357:in `paths'
	from /usr/share/rubygems/rubygems.rb:379:in `path'
	from /usr/share/rubygems/rubygems/specification.rb:797:in `dirs'
	from /usr/share/rubygems/rubygems/specification.rb:661:in `each_normal'
	from /usr/share/rubygems/rubygems/specification.rb:672:in `_all'
	from /usr/share/rubygems/rubygems/specification.rb:825:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:867:in `find'
	from /usr/share/rubygems/rubygems/specification.rb:867:in `find_inactive_by_path'
	from /usr/share/rubygems/rubygems.rb:175:in `try_activate'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/share/rubygems/rubygems.rb:1097:in `<top (required)>'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/one/ruby/onedb/onedb_backend.rb:18:in `<top (required)>'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/one/ruby/onedb/onedb.rb:25:in `<top (required)>'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/bin/onedb:60:in `<main>'

```

**Details**
 - Affected Component: all Ruby?
 - Version: 5.12, master

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
As described in the text, problem is caused by existence of multiple `rubygems` in the system. Specific version always comes with the Ruby interpreter, which can be upgraded by user via [rubygems-update](https://rubygems.org/gems/rubygems-update/) to any other version (this is the very edge case, majority of users will not have anything else than what's in the system). Both versions live alongside in different directories, and based on default load paths the custom new one has a precedence because it's put into `site_ruby` directories (output from Ubuntu 18.04):

```
$ ruby -e 'STDERR.puts $LOAD_PATH'
/usr/local/lib/site_ruby/2.5.0                # <---- Here finds custom RubyGems
/usr/local/lib/x86_64-linux-gnu/site_ruby
/usr/local/lib/site_ruby
/usr/lib/ruby/vendor_ruby/2.5.0
/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.5.0
/usr/lib/ruby/vendor_ruby
/usr/lib/ruby/2.5.0                           # <----- Here is the default RubyGems
/usr/lib/x86_64-linux-gnu/ruby/2.5.0
```

Since we package all Ruby dependencies, idea of #4303 was to remove all site/vendor directories from `$LOAD_PATH` not to use any custom gems installed in the system (possibly in different versions) and affect badly the OpenNebula. Problem is that `rubygems` are loaded automatically (unless disabled on compile time or via command line option, e.g. `ruby --disable-gems`) before we can adjust the `$LOAD_PATH`. After we cleanup `$LOAD_PATH`, the different version is loaded again later over the previously loaded version and code fails.

Various solutions how to fix the problem in OpenNebula code will follow....

# Workaround

Workaround is to detect the directory where custom RubyGems are loaded from, e.g.:

```
# ruby -e 'puts $LOADED_FEATURES.grep(/rubygems.rb/)' 2>/dev/null
/usr/local/lib/site_ruby/2.5.0/rubygems.rb
```

and if path is from site_ruby, **review all content of that directory**, e.g.:

```
find /usr/local/lib/site_ruby/2.5.0/
```

and disable the location by renaming it, e.g.:

```
mv /usr/local/lib/site_ruby/2.5.0 /usr/local/lib/site_ruby/2.5.0-disabled
```

After that, validate that default RubyGems from non-site/vendor specific path are used, e.g.:

```
# ruby -e 'puts $LOADED_FEATURES.grep(/rubygems.rb/)'
/usr/lib/ruby/2.5.0/rubygems.rb
```

**Comment by vholer** [comment]
## Solution 1 - Simple

Simplest solution is to modify the shared loaders in Ruby code:

```
if File.directory?(GEMS_LOCATION)
    Gem.use_paths(GEMS_LOCATION)
    $LOAD_PATH.reject! {|l| l =~ /(vendor|site)_ruby/ }
end
```

and change order of `$LOAD_PATH` to happen first, followed by explicit reload of rubygems and settings paths. Looks like the real problem comes from the fact that secondly loaded rubygems sometimes later loses the path to our `GEMS_LOCATION`. E.g.,

```
if File.directory?(GEMS_LOCATION)
    $LOAD_PATH.reject! {|l| l =~ /(vendor|site)_ruby/ }
    require 'rubygems'
    Gem.use_paths(File.realpath(GEMS_LOCATION))
end
```

This still results in a lot of Ruby warnings just related to RubyGems, but at least the commands / services work.

```
...
/usr/lib/ruby/2.5.0/rubygems/specification.rb:1761: warning: already initialized constant Gem::Specification::DateTimeFormat
/usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1676: warning: previous definition of DateTimeFormat was here
/usr/lib/ruby/2.5.0/rubygems/exceptions.rb:276: warning: already initialized constant Gem::UnsatisfiableDepedencyError
/usr/local/lib/site_ruby/2.5.0/rubygems/exceptions.rb:292: warning: previous definition of UnsatisfiableDepedencyError was here
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:12: warning: already initialized constant Kernel::RUBYGEMS_ACTIVATION_MONITOR
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:12: warning: previous definition of RUBYGEMS_ACTIVATION_MONITOR was here
```

**Comment by vholer** [comment]
## Solution 2 - Fail to start with error message

We can detect if RubyGems version hasn't changed between 2 requires from different load paths, and fail to continue with clear message telling user that he has multi RubyGems version installed.

```
if File.directory?(GEMS_LOCATION)
    require 'rubygems'
    old = Gem::VERSION

    $LOAD_PATH.reject! {|l| l =~ /(vendor|site)_ruby/ }
    require 'rubygems'

    if Gem::VERSION != old
        STDERR.puts 'ERROR: System has multiple RubyGems versions' \
                    " installed (#{old}, #{Gem::VERSION})"
        exit -1
    end

    Gem.use_paths(GEMS_LOCATION)
end
```

This doesn't avoid tons of Ruby warnings (unless they are disabled by `$VERBOSE=nil`), but at least user has a clue why we fail:

```
...
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:12: warning: already initialized constant Kernel::RUBYGEMS_ACTIVATION_MONITOR
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:12: warning: previous definition of RUBYGEMS_ACTIVATION_MONITOR was here
ERROR: System has multiple RubyGems versions installed (3.1.4, 2.7.6)
```

## Solution 2b (1+2) - Run, but warn about multiple RubyGems

Instead of `exit` on multiple versions, just continue.

**Comment by vholer** [comment]
## Solution 3 - Avoid removing already used paths

Idea would be not to remove specific vendor/site_ruby paths, if there are already some modules loaded from them. That would be probably the most transparent transparent approach, but if we leave some of the vendor/site_ruby only because of RubyGems, they might be used to serve any other gems we depend on in different versions we require. E.g.,

```
if File.directory?(GEMS_LOCATION)
    loaded = $LOADED_FEATURES.map {|p| File.dirname(p) }
    filter = $LOAD_PATH.select {|p| p =~ /(vendor|site)_ruby/ }
    filter.each do |p|
        $LOAD_PATH.delete(p)
        if loaded.include?(p)
            warn("WARNING: Still using directory '#{p}'")
            $LOAD_PATH << p 
        end
    end

    Gem.use_paths(File.realpath(GEMS_LOCATION))
end
```

In the `$LOADED_FEATURES`, there is a list of filenames of loaded Ruby parts, e.g.:

```
enumerator.so
thread.rb
rational.so
complex.so
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/enc/encdb.so
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/enc/trans/transdb.so
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/rbconfig.rb
/usr/local/lib/site_ruby/2.5.0/rubygems/compatibility.rb
/usr/local/lib/site_ruby/2.5.0/rubygems/defaults.rb
/usr/local/lib/site_ruby/2.5.0/rubygems/deprecate.rb
...
```

in this list we find used common path `/usr/local/lib/site_ruby/2.5.0` and don't remove it from `$LOAD_PATH`.

**Comment by vholer** [comment]
## Solution 4 - Don't remove `site_ruby` directories

For previous #4304 problem, it should be enough only to remove `vendor_ruby` directories where distribution packages puts gems (on Debian) to avoid use of conflicting gems. Removing also `site_ruby` only ensures that the Ruby environment is as close to default distribution one without user customizations.

Sample code:

```
if File.directory?(GEMS_LOCATION)
    Gem.use_paths(GEMS_LOCATION)
    $LOAD_PATH.reject! {|l| l =~ /vendor_ruby/ }
end
```

**Comment by vholer** [comment]
## Solution 5 - Move `site_ruby` at the end of load path

Modified approach 3, but move site_ruby at the and of path list always. Doesn't break already loaded modules and provides consistent approach to `$LOAD_PATH` no matter if rubygems are loaded from base or site_ruby.

```
if File.directory?(GEMS_LOCATION)
    site = $LOAD_PATH.select {|f| f =~ /site_ruby/ }
    $LOAD_PATH.reject! {|l| l =~ /(vendor|site)_ruby/ }
    $LOAD_PATH.concat(site)
    require 'rubygems'
    Gem.use_paths(File.realpath(GEMS_LOCATION))
end
```

**Comment by vholer** [comment]
## Summary

1 and 2 -  unfortunately doesn't work on C7 (can't override RubyGems 2.7 back to 2.0)
3 - not sure if leaving share/site_ruby, but removing lib64/site_ruby, can't make any harm when overrides there come with shared libraries
4 - site_ruby might contain code which overrides A) distribution default B) OpenNebula code
5 - still allows using site_ruby as 4 but A) not to override "most" of distribution default B) still overrides OpenNebula code

Since 5 doesn't fully avoid A and still affects B, the most sane is probably go for 4 and leave site_ruby active as in 5.10.

**Comment by vholer** [comment]
PRs to merge:
- one https://github.com/OpenNebula/one-ee/pull/33 into
  - **master**
  - cherry-pick into **one-5.12**
- docs https://github.com/OpenNebula/docs/pull/1218 (shared w/ different pending issue) into
  - one-5.12-maintenance
