### ISSUE TITLE
DB migration to 5.12 failed due to undefined method `after' for nil

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5013]
**Description**
A database migration from 5.10 to 5.12 might fail if VM in the pool (?most likely?) doesn't have `DEPLOY_ID`.

```
> Database migrated from 5.10.0 to 5.12.0 (OpenNebula 5.12.0) by onedb command.
>
> >>> Running migrators for local tables
>   > Running migrator /usr/lib/one/ruby/onedb/local/5.10.0_to_5.12.0.rbm
> All custom_attrs will be used as networks
>
> undefined method `after' for nil:NilClass
> /usr/share/one/gems-dist/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:59:in `after'
> local/5.10.0_to_5.12.0.rb:221:in `block (2 levels) in feature_3859'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:152:in `block in each'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:238:in `block (2 levels) in fetch_rows'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:238:in `each'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:238:in `block in fetch_rows'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:151:in `_execute'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `block in execute'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/connecting.rb:253:in `synchronize'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `execute'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:1089:in `execute'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:276:in `execute'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/adapters/mysql2.rb:236:in `fetch_rows'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/dataset/actions.rb:152:in `each'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/dataset.rb:51:in `fetch'
> local/5.10.0_to_5.12.0.rb:214:in `block in feature_3859'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/transactions.rb:254:in `_transaction'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/transactions.rb:229:in `block in transaction'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/connecting.rb:253:in `synchronize'
> /usr/share/one/gems-dist/gems/sequel-5.31.0/lib/sequel/database/transactions.rb:195:in `transaction'
> local/5.10.0_to_5.12.0.rb:212:in `feature_3859'
> local/5.10.0_to_5.12.0.rb:36:in `up'
> /usr/lib/one/ruby/onedb/onedb.rb:393:in `apply_migrators'
> /usr/lib/one/ruby/onedb/onedb.rb:291:in `upgrade'
> /usr/bin/onedb:439:in `block (2 levels) in <main>'
> /usr/lib/one/ruby/cli/command_parser.rb:477:in `call'
> /usr/lib/one/ruby/cli/command_parser.rb:477:in `run'
> /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
> /usr/bin/onedb:336:in `new'
> /usr/bin/onedb:336:in `<main>'
>
>
> The database will be restored
```

https://github.com/OpenNebula/one-ee-tools/blob/dd7441458a200ad78d4a5a912d8b1ee79e0f6c68/src/onedb/local/5.10.0_to_5.12.0.rb#L221

**Details**
 - Affected Component: Core
 - Version: 5.12.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee-tools/pull/1)
- [docs](https://github.com/OpenNebula/docs/pull/1267)
