### ISSUE TITLE
LXD containers dead after node reboot

### ISSUE THREAD

**Issue by thee233** [OpenNebula/one#5127]
**Description**

Minione LXD hypervisor cannot start containers after node reboot in Opennebula 5.12.0.1 on Bionic host

Happens on clean instance deployed with minione, on fresh baremetal based Ubuntu 18.04.

**To Reproduce**

Create containers and reboot a machine. 
Sunstone and `onevm` state that containers are running, but in fact they're not:

````
root@generic-bionic:~# onevm list

  ID USER     GROUP    NAME                                                                                STAT  CPU     MEM HOST                                                          TIME
   5 oneadmin oneadmin ghj                                                                                 runn  0.1      2M localhost                                                 0d 00h28
   4 tadziu   oneadmin asdf                                                                                runn  0.1      2M localhost                                                 0d 18h55
root@generic-bionic:~# lxc list
+-------+---------+------+------+------------+-----------+
| NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+------+------+------------+-----------+
| one-0 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-1 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-2 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-3 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-4 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-5 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+

````
Sunstone also refuse to take any reboot/stop/poweroff action on the containers with error:

```
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/lxd/reset 'one-4' 'localhost' 4 localhost
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: reboot: --- Starting container ---
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: reboot: Name: one-4
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Remote: unix://
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Architecture: x86_64
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Created: 2020/10/12 14:19 UTC
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Status: Stopped
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Type: persistent
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Profiles: default
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]:
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Log:
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]:
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc one-4 20201013091903.541 WARN conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc one-4 20201013091903.541 ERROR start - start.c:start:2028 - No such file or directory - Failed to exec "/sbin/init"
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc one-4 20201013091903.541 ERROR sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 7)
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc one-4 20201013091903.541 WARN network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 14
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc one-4 20201013091903.542 ERROR lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc one-4 20201013091903.542 ERROR start - start.c:__lxc_start:1939 - Failed to spawn container "one-4"
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: lxc 20201013091903.543 WARN commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]:
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: /var/tmp/one/vmm/lxd/client.rb:102:in `wait': {"type"=>"sync", "status"=>"Success", "status_code"=>200, "operation"=>"", "error_code"=>0, "error"=>"", "metadata"=>{"id"=>"cecfe476-112c-43d1-bf23-b0c77f920ffd", "class"=>"task", "description"=>"Starting container", "created_at"=>"2020-10-13T11:19:03.293600861+02:00", "updated_at"=>"2020-10-13T11:19:03.293600861+02:00", "status"=>"Failure", "status_code"=>400, "resources"=>{"containers"=>["/1.0/containers/one-4"]}, "metadata"=>nil, "may_cancel"=>false, "err"=>"Failed to run: /usr/lib/lxd/lxd forkstart one-4 /var/lib/lxd/containers /var/log/lxd/one-4/lxc.conf: "}} (LXDError)
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:517:in `wait?'
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:529:in `change_state'
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:211:in `start'
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:257:in `reboot'
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/reboot:37:in `<main>'
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: ExitCode: 1
Tue Oct 13 11:19:03 2020 [Z0][VMM][I]: Failed to execute virtualization driver operation: reset.
Tue Oct 13 11:19:03 2020 [Z0][VMM][E]: Error rebooting-hard VM, assume it's still running
```
Furthermore those containers cannot be terminated via Sunstone. The only way to bring container allive is to force
recover delete-recreate action, this however purges all persistent data written to LXD instance. 

I've tried to bring containers with `lxc start` and that gave some actual errors. 

1. By default on Bionic LXC couldn't find libdqlite.so.0. Fixed with appeding `LD_LIBRARY_PATH="/usr/lib/lxd/"` in 
`/etc/enviroment` 
2. Fixing that got me one step further but still containers fail to start:
```
Error: Failed to run: /usr/lib/lxd/lxd forkstart one-5 /var/lib/lxd/containers /var/log/lxd/one-5/lxc.conf: 
Try `lxc info --show-log one-5` for more info
```
However running `/usr/lib/lxd/lxd forkstart one-5 /var/lib/lxd/containers /var/log/lxd/one-5/lxc.conf` manually exits with 0 status, so it seems ok but it apparently does not work:
```
root@generic-bionic:~# /usr/lib/lxd/lxd forkstart one-5 /var/lib/lxd/containers /var/log/lxd/one-5/lxc.conf
root@generic-bionic:~# lxc start one-5
Error: Failed to run: /usr/lib/lxd/lxd forkstart one-5 /var/lib/lxd/containers /var/log/lxd/one-5/lxc.conf: 
Try `lxc info --show-log one-5` for more info
```
Logs:
```
root@generic-bionic:~# lxc info --show-log one-5
Name: one-5
Remote: unix://
Architecture: x86_64
Created: 2020/10/13 08:46 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc one-5 20201013092958.412 WARN     conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance
lxc one-5 20201013092958.413 ERROR    start - start.c:start:2028 - No such file or directory - Failed to exec "/sbin/init"
lxc one-5 20201013092958.413 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 7)
lxc one-5 20201013092958.413 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 20
lxc one-5 20201013092958.413 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc one-5 20201013092958.414 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "one-5"
lxc 20201013092958.415 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"
```
More interesting debug information can be found in system journal (-r):

```
Oct 13 11:36:47 generic-bionic systemd-networkd[5086]: one-5-0: Lost carrier
Oct 13 11:36:47 generic-bionic systemd-networkd[5086]: one-5-0: Link DOWN
Oct 13 11:36:47 generic-bionic systemd-timesyncd[4908]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Oct 13 11:36:47 generic-bionic lxd[5339]: t=2020-10-13T11:36:47+0200 lvl=eror msg="Failed starting container" action=start created=2020-10-13T10:46:18+0200 ephemeral=false name=one-5 
Oct 13 11:36:47 generic-bionic kernel: br44: port 3(one-5-0) entered forwarding state
Oct 13 11:36:47 generic-bionic kernel: br44: port 3(one-5-0) entered blocking state
Oct 13 11:36:47 generic-bionic kernel: IPv6: ADDRCONF(NETDEV_CHANGE): one-5-0: link becomes ready
Oct 13 11:36:47 generic-bionic kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Oct 13 11:36:47 generic-bionic kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: using nameserver 127.0.0.53#53
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: reading /etc/resolv.conf
Oct 13 11:36:47 generic-bionic systemd-networkd[5086]: one-5-0: Gained carrier
Oct 13 11:36:47 generic-bionic kernel: eth0: renamed from veth5VTP3B
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: using nameserver 127.0.0.53#53
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: reading /etc/resolv.conf
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: using nameserver 127.0.0.53#53
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: reading /etc/resolv.conf
Oct 13 11:36:47 generic-bionic systemd-timesyncd[4908]: Network configuration changed, trying to establish connection.
Oct 13 11:36:47 generic-bionic systemd-timesyncd[4908]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: using nameserver 127.0.0.53#53
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: reading /etc/resolv.conf
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: using nameserver 127.0.0.53#53
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: reading /etc/resolv.conf
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-devices-virtual-net-one\x2d5\x2d0.device.d: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-devices-virtual-net-one\x2d5\x2d0.device.requires: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-devices-virtual-net-one\x2d5\x2d0.device.wants: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-subsystem-net-devices-one\x2d5\x2d0.device.d: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-subsystem-net-devices-one\x2d5\x2d0.device.requires: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-subsystem-net-devices-one\x2d5\x2d0.device.wants: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-devices-virtual-net-veth5VTP3B.device.d: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-devices-virtual-net-veth5VTP3B.device.requires: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-devices-virtual-net-veth5VTP3B.device.wants: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-subsystem-net-devices-veth5VTP3B.device.d: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-subsystem-net-devices-veth5VTP3B.device.requires: Permission denied
Oct 13 11:36:47 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/sys-subsystem-net-devices-veth5VTP3B.device.wants: Permission denied
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: using nameserver 127.0.0.53#53
Oct 13 11:36:47 generic-bionic dnsmasq[5255]: reading /etc/resolv.conf
Oct 13 11:36:47 generic-bionic systemd-udevd[19211]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Oct 13 11:36:47 generic-bionic systemd-timesyncd[4908]: Network configuration changed, trying to establish connection.
Oct 13 11:36:47 generic-bionic kernel: IPv6: ADDRCONF(NETDEV_UP): one-5-0: link is not ready
Oct 13 11:36:47 generic-bionic kernel: device one-5-0 entered promiscuous mode
Oct 13 11:36:47 generic-bionic kernel: br44: port 3(one-5-0) entered disabled state
Oct 13 11:36:47 generic-bionic kernel: br44: port 3(one-5-0) entered blocking state
Oct 13 11:36:47 generic-bionic networkd-dispatcher[4991]: WARNING:Unknown index 23 seen, reloading interface list
Oct 13 11:36:47 generic-bionic systemd-udevd[19210]: Could not generate persistent MAC address for veth5VTP3B: No such file or directory
Oct 13 11:36:47 generic-bionic systemd-networkd[5086]: one-5-0: Link UP
Oct 13 11:36:46 generic-bionic systemd-udevd[19210]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Oct 13 11:36:46 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/var-lib-lxd-devices-one\x2d5-disk.context.context.mount.d: Permission denie
Oct 13 11:36:46 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/var-lib-lxd-devices-one\x2d5-disk.context.context.mount.requires: Permissio
Oct 13 11:36:46 generic-bionic systemd[6270]: Failed to canonicalize path /home/tadziu/.config/systemd/user/var-lib-lxd-devices-one\x2d5-disk.context.context.mount.wants: Permission d
```
Honestly i do not quite understand, why i got permission errors for my home user, since LXC commands are being invoked as root and i do not know whether those perms problem is relevant.

This issue is reproducible with any LXD image from marketplace as well as default minione deployed generic CentOS so its clear that it is not image related.  

**Expected behavior**
Proper containers start on system reboots. 

**Details**
 - Affected Component: Minione LXD instance 
 - Hypervisor: LXD
 - Version: 5.12.0.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
Can you apply the following commits 

- https://github.com/OpenNebula/one/commit/aa379a100e08a40b98dc9609a68ad2ba156db4e5
- https://github.com/OpenNebula/one/commit/4516352239950c79e9d0c4e655a1c9e7e60cc048

replace the following files in the frontend by the ones in the commits

- `/var/lib/one/remotes/im/lxd-probes.d/vm/status/state.rb`
- `/var/lib/one/remotes/im/lib/probe_db.rb`

and issue a `onehost sync --force` to sync them to the hypersivor. After that, see if the containers are no longer reported RUNNING. 

The problem is those containers are being reported RUNNING by OpenNebula, they exist on the node, but they don't have the container image mounted on the container rootfs path. Then you see:

> lxc one-5 20201013092958.413 ERROR    start - start.c:start:2028 - No such file or directory - Failed to exec "/sbin/init"

Because there is no `/sbin/init` file in the container rootfs. In order to manually fix that, you need to mount the container images on the container rootfs path and its mountpoints. 

Here is an example of a VM with contextualization and a single disk.

```
root@cygnus:~# lxc list
+-------+---------+------+------+------------+-----------+
| NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+------+------+------------+-----------+
| one-0 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-1 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
| one-2 | STOPPED |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
root@cygnus:~# lsblk 
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0  364K  0 loop /var/lib/one/datastores/0/2/mapper/disk.1
sda       8:0    0   60G  0 disk 
├─sda1    8:1    0 59.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sr0      11:0    1  366K  0 rom  /mnt
nbd0     43:0    0    1G  0 disk /var/lib/lxd/storage-pools/default/containers/one-2/rootfs
```

This is how it should look prior to manually starting the container. The VM disk is mapped to `/dev/nbd0` and the context ISO is mapped to `/dev/loop0`

**Comment by thee233** [comment]
Yes those patches fix containers status in Sunstone. That is a good progress direction however onevm still returns false status and my primary concern is not fixed - mounts are still ephemeral. 

However I can start containers via Sunstone after reboot and my data is not lost i'd like to keep those mount persistent in some way or another. Is that possible? I've just started fiddling around with nebula since openstack is hard to maintain for our team. So excuse noobish question but can we expect same problem with LXD nodes in production scenario with properly deployed cloud or is it just evaluation-minione related issue?

Nebulas KVM instances works as expected so we've even started developing some tools with You api however LXD is crucial for our on premises infrastructure.

**Comment by dann1** [comment]
> Yes those patches fix containers status in Sunstone

> onevm still returns false status

If Sunstone shows the correct status then `onevm list` should report the same status. Can you clarify this ?

> my primary concern is not fixed - mounts are still ephemeral.

If the node is forcibly rebooted/powered off, then you won't have the mounts when it comes online. However, if OpenNebula reports the containers as powered off, which they should be with the patches, because they exist in the node, then you just issue a `onevm resume` or Resume in Sunstone and the mounts should be issued as usual.

The mounts are issued after creating the container and prior to starting it. IF the container VM is rebooted the mounts persist. If the container VM is powered off, the mounts are cleaned and the container is deleted afterwards. Then if the container is started again, it is recreated and mounts are issued as well.

> So excuse noobish question but can we expect same problem with LXD nodes in production scenario with properly deployed cloud or is it just evaluation-minione related issue?

For production environments you should get the [OpenNebula enterprise edition](https://opennebula.io/subscriptions/) which comes with access to the enterprise repository packages. Those packages come with all of the fixes (for example the provided fix is there) and the ability to upgrade you OpenNebula deployment, and of course, enterprise support.

**Comment by thee233** [comment]
> If Sunstone shows the correct status then `onevm list` should report the same status. Can you clarify this ?

what i've missed here is that it takes few minutes after node up for the status to become expected:
```
root@generic-bionic:~# uptime
 10:21:41 up 0 min,  2 users,  load average: 4.38, 1.45, 0.51
root@generic-bionic:~# onevm list
  ID USER     GROUP    NAME                                                                             STAT  CPU     MEM HOST                                                        TIME
   0 tadziu   oneadmin asdf                                                                             runn  0.1      2G localhost                                               2d 22h03
root@generic-bionic:~# onevm list
  ID USER     GROUP    NAME                                                                             STAT  CPU     MEM HOST                                                        TIME
   0 tadziu   oneadmin asdf                                                                             poff  0.1      2G localhost                                               2d 22h10

```
i've just didn't checked twice my bad. 

> The mounts are issued after creating the container and prior to starting it. IF the container VM is rebooted the mounts persist. If the container VM is powered off, the mounts are cleaned and the container is deleted afterwards. Then if the container is started again, it is recreated and mounts are issued as well.

okay, so in case of the power loss or a single minione server instance failure we just need a startup service that iterates over poffed containers and just starts them the same way via API the same way a user would do it manually right?

thanks for Your help, if the platform passes all of our tests we surely consider going enterprise.

**Comment by dann1** [comment]
> okay, so in case of the power loss or a single minione server instance failure we just need a startup service that iterates over poffed containers and just starts them the same way via API the same way a user would do it manually right?

That is the case, if you want to test it. You can sort of simulate a power failure. To do so:

Manually stop the container

```
lxc stop one-<vm_id>
```

umount the images. Following the example provided:

```
umount /var/lib/one/datastores/0/2/mapper/disk.1 # umount context disk
umount /var/lib/lxd/storage-pools/default/containers/one-2/rootfs # umount rootfs image
```

unmap the images

```
losetup -d /dev/loop0
qemu-nbd -d /dev/nbd0
```

And the monitoring system should update the VM status when it detects the container being powered off. Then try to resume the VM and see if it works.
