### ISSUE TITLE
LXD fails to map disk due to missing `file` command

### ISSUE THREAD

**Issue by wirwolf** [OpenNebula/one#5183]
OS: Ubuntu Focal
OpenNebula 5.12.0.3
**To Reproduce**
create new lxd container

**Details**
 - Affected Component: mayby Storage
 - Hypervisor: lxd
 - Version: 3.0.4

```
Thu Nov 19 14:15:15 2020 [Z0][VM][I]: New state is ACTIVE
Thu Nov 19 14:15:15 2020 [Z0][VM][I]: New LCM state is PROLOG
Thu Nov 19 14:15:24 2020 [Z0][VM][I]: New LCM state is BOOT
Thu Nov 19 14:15:24 2020 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/12/deployment.0
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: pre: Executed "sudo -n ip link add name br1 type bridge ".
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: pre: Executed "sudo -n ip link set br1 up".
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: pre: Executed "sudo -n ip link add eth0.2 mtu 1500 type vxlan id 2 group 239.0.0.2 ttl 16 dev eth0 ".
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: pre: Executed "sudo -n ip link set eth0.2 up".
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: pre: Executed "sudo -n ip link set eth0.2 master br1".
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: ExitCode: 0
Thu Nov 19 14:15:25 2020 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/lxd/deploy '/var/lib/one//datastores/102/12/deployment.0' 'node-master-2.awedo.space' 12 node-master-2.awedo.space
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: deploy: Processing disk 0
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: /usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - file (Errno::ENOENT)
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /usr/lib/ruby/2.7.0/open3.rb:101:in `popen3'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /usr/lib/ruby/2.7.0/open3.rb:281:in `capture3'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lib/command.rb:32:in `execute'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:548:in `new_disk_mapper'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:416:in `setup_disk'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:316:in `block in setup_storage'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:314:in `each'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/container.rb:314:in `setup_storage'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: from /var/tmp/one/vmm/lxd/deploy:61:in `<main>'
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: ExitCode: 1
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: clean: Executed "sudo -n ip link delete eth0.2".
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: clean: Executed "sudo -n ip link delete br1".
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: ExitCode: 0
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Thu Nov 19 14:15:26 2020 [Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
Thu Nov 19 14:15:26 2020 [Z0][VMM][E]: Error deploying virtual machine
Thu Nov 19 14:15:26 2020 [Z0][VM][I]: New LCM state is BOOT_FAILURE
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by wirwolf** [comment]
storage config
```
ALLOW_ORPHANS	NO	 
DISK_TYPE	FILE	 
DS_MIGRATE	YES	 
RESTRICTED_DIRS	/	 
SAFE_DIRS	/var/tmp	 
SHARED	NO	 
TM_MAD	ssh	 
TYPE	SYSTEM_DS	 
```

**Comment by wirwolf** [comment]
@carlosms

**Comment by dann1** [comment]
This error is ruby complaining about the command not existing at all

```
irb(main):002:0> require 'open3'
=> true
irb(main):003:0> o, e, s = Open3.capture3('users')
=> ["dann1\n", "", #<Process::Status: pid 67289 exit 0>]
irb(main):004:0> o, e, s = Open3.capture3('usersx')
Traceback (most recent call last):
        8: from /usr/bin/irb:23:in `<main>'
        7: from /usr/bin/irb:23:in `load'
        6: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
        5: from (irb):4
        4: from /usr/lib/ruby/2.7.0/open3.rb:281:in `capture3'
        3: from /usr/lib/ruby/2.7.0/open3.rb:101:in `popen3'
        2: from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
        1: from /usr/lib/ruby/2.7.0/open3.rb:213:in `spawn'
Errno::ENOENT (No such file or directory - usersx)
```

The command which runs in [these lines](https://github.com/OpenNebula/one/blob/2948346c3d87254b5581d885871bf7d8df753146/src/vmm_mad/remotes/lib/lxd/container.rb#L546-L548), which is [this command](https://github.com/OpenNebula/one/blob/2948346c3d87254b5581d885871bf7d8df753146/src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb#L66) sems to be absent in your node. For some reason oneadmin cannot run `file -L -s`

**Comment by wirwolf** [comment]
when i install `file` pkg in my system and redeploy the container - the problem is solved.  Mayby add in opennebula-node-lxd pkg dependency `file`

**Comment by dann1** [comment]
the file package should already be installed as a very basic package. Even the minimal images from the LXD image repositories come with the file package. @rsmontero should we add this requirement to the lxd node package ?

**Comment by christian7007** [comment]
It seems that the package is listed in the Ubuntu 20.04 (Focal Fossa) manifest: http://releases.ubuntu.com/20.04/ubuntu-20.04.3-desktop-amd64.manifest
