### ISSUE TITLE
onedb fsck typo in image check

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5262]
**Description**

Problematic line:
https://github.com/OpenNebula/one/blob/4e670bf7bf70ac7e826456da60abadd7c7ca1447/src/onedb/fsck/image.rb#L132

Error:

```
$ onedb fsck
Sqlite database backup stored in /var/lib/one/one.db_2021-2-22_12:37:31.bck
Use 'onedb restore' to restore the DB.

Cluster 0 has not the proper reserved VNC ports

undefined local variable or method `i_e' for #<BackEndSQLite:0x00005576db715898>
Did you mean?  h_e
/usr/lib/one/ruby/onedb/fsck/image.rb:133:in `block (3 levels) in check_image'
/usr/share/ruby/set.rb:328:in `each_key'
/usr/share/ruby/set.rb:328:in `each'
/usr/lib/one/ruby/onedb/fsck/image.rb:125:in `block (2 levels) in check_image'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/dataset/actions.rb:152:in `block in each'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:345:in `block (2 levels) in fetch_rows'
/usr/share/one/gems-dist/gems/sqlite3-1.4.2/lib/sqlite3/resultset.rb:134:in `each'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:334:in `block in fetch_rows'
/usr/share/one/gems-dist/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:339:in `query'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:200:in `block (2 levels) in _execute'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:200:in `block in _execute'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:193:in `_execute'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:139:in `execute'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/dataset/actions.rb:1093:in `execute'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:327:in `fetch_rows'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/dataset/actions.rb:152:in `each'
/usr/lib/one/ruby/onedb/fsck/image.rb:36:in `block in check_image'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/usr/share/one/gems-dist/gems/sequel-5.41.0/lib/sequel/database/transactions.rb:195:in `transaction'
/usr/lib/one/ruby/onedb/fsck/image.rb:35:in `check_image'
/usr/lib/one/ruby/onedb/fsck.rb:434:in `fsck'
/usr/lib/one/ruby/onedb/onedb.rb:486:in `fsck'
/usr/bin/onedb:476:in `block (2 levels) in <main>'
/usr/lib/one/ruby/cli/command_parser.rb:482:in `run'
/usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
/usr/bin/onedb:346:in `new'
/usr/bin/onedb:346:in `<main>'

Error running fsck version 6.0.0
The database will be restored
Sqlite database backup restored in /var/lib/one/one.db
```

Please backport for 5.12 EE (LTS).

**Details**
 - Affected Component: onedb
 - Version: 5.12+

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 5.12 and master:

- [code](https://github.com/OpenNebula/one-ee/pull/861)

PR to merge in one-5.12-maintenance:

- [docs](https://github.com/OpenNebula/docs/pull/1481)
