### ISSUE TITLE
Issue when adding second YubiKey on Sunstone

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5492]
**Description**
When trying to add a new security key, after pushing the key's button Sunstone replies "It appears there was a server exception. Please check server's log."

**To Reproduce**
Add a second YubiKey on Sunstone.

**Expected behavior**
No exception should be shown.

**Details**
 - Affected Component: Sunstone
 - Version: 6.0.3 and master.

**Additional context**
Log file:

```
2021-08-09 16:31:59 - NoMethodError - undefined method `id' for WebAuthn::OriginVerificationError:OpenNebula::Error:
#011/usr/lib/one/sunstone/models/OpenNebulaJSON/UserJSON.rb:124:in `enable_security_key'
#011/usr/lib/one/sunstone/models/OpenNebulaJSON/UserJSON.rb:57:in `perform_action'
#011/usr/lib/one/sunstone/models/SunstoneServer.rb:226:in `perform_action'
#011/usr/lib/one/sunstone/sunstone-server.rb:1224:in `block in <main>'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:253:in `call'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
#011/usr/share/one/gems-dist/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
#011/usr/share/one/gems-dist/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
#011/usr/share/one/gems-dist/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
#011/usr/share/one/gems-dist/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
#011/usr/share/one/gems-dist/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
#011/usr/share/one/gems-dist/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
#011/usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
#011/usr/share/one/gems-dist/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
#011/usr/share/one/gems-dist/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
#011/usr/share/one/gems-dist/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
#011/usr/share/one/gems-dist/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
#011/usr/share/one/gems-dist/gems/thin-1.8.0/lib/thin/connection.rb:50:in `block in process'
#011/usr/share/one/gems-dist/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
will be addressed in FireEdge Sunstone
