### ISSUE TITLE
Unable to start  Sunstone due to YAML load problem

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#5551]
**Description**
When trying to start Sunstone, the following error is rised:

```
Unknown alias: provisionactions
```

This comes from views configuration YAML, they fail to load:

```
irb(main):002:0> YAML.load_file('src/sunstone/etc/sunstone-views/mixed/cloud.yaml')
/home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: provisionactions (Psych::BadAlias)
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /home/alex/.gem/ruby/3.0.0/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
```

The problematic section seems to be this `actions: &provisionactions`.

**To Reproduce**
Start Sunstone on master.

**Expected behavior**
It shouldn't fail to load YAML.

**Details**
 - Affected Component: Sunstone.
 - Version: 5.12 and master.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
ruby 3.0 is currently not supported
