### ISSUE TITLE
Dependency error for onezone command

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5567]
**Description**
When installing the CLI in a node different than the Frontend, `onezone` command will throw an error because of an unmet dependency:

```
$ onezone list
Traceback (most recent call last):
5: from /usr/bin/onezone:39:in `<main>'
4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
2: from /usr/lib/one/ruby/cli/one_helper/onezone_helper.rb:19:in `<top (required)>'
1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- CommandManager (LoadError)
```

**Expected behavior**
Every command dependency should be correctly installed.

**Details**
 - Affected Component: CLI
 - Version:5.12 & master

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
PRs to merge in 6.0 and master (wait until packages PR is reviewed):

- [packages](https://github.com/OpenNebula/packages/pull/257)
- [docs](https://github.com/OpenNebula/docs/pull/2011)
