### ISSUE TITLE
Error when deploying an app exported from marketplace in vCenter datastore

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#5754]
**Description**
When exporting an application from the marketplace and trying to run it in vCenter, it gives the following error:

```
Mon Feb 28 16:58:13 2022: DEPLOY: ERROR: deploy: Deploy of VM 3 on vCenter cluster Cluster2 with /var/lib/one/vms/3/deployment.0 failed due to "GenericVmConfigFault: Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. "on attempt #0. Deploy of VM 3 on vCenter cluster Cluster2 with /var/lib/one/vms/3/deployment.0 failed due to "GenericVmConfigFault: Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. "on attempt #0. ["/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3293:in `rescue in poweron'", "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3289:in `poweron'", "/var/lib/one/remotes/vmm/vcenter/deploy:136:in `<main>'"] ERROR: deploy: Deploy of VM 3 on vCenter cluster Cluster2 with /var/lib/one/vms/3/deployment.0 failed due to "GenericVmConfigFault: Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. "on attempt #1. Deploy of VM 3 on vCenter cluster Cluster2 with /var/lib/one/vms/3/deployment.0 failed due to "GenericVmConfigFault: Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. "on attempt #1. ["/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3293:in `rescue in poweron'", "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3289:in `poweron'", "/var/lib/one/remotes/vmm/vcenter/deploy:136:in `<main>'"] ERROR: deploy: Deploy of VM 3 on vCenter cluster Cluster2 with /var/lib/one/vms/3/deployment.0 failed due to "GenericVmConfigFault: Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. "on attempt #2. Deploy of VM 3 on vCenter cluster Cluster2 with /var/lib/one/vms/3/deployment.0 failed due to "GenericVmConfigFault: Unsupported or invalid disk type 2 for 'scsi0:0'. Ensure that the disk has been imported. "on attempt #2. ["/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3293:in `rescue in poweron'", "/usr/lib/one/ruby/vcenter_driver/virtual_machine.rb:3289:in `poweron'", "/var/lib/one/remotes/vmm/vcenter/deploy:136:in `<main>'"]
```

**To Reproduce**

- Import a VM template from vCenter.
- Remove all the disks.
- Export an app from the marketplace.
- Add the image to the above template.
- Instantiate it.

Example:

```
 <ID>12</ID>
  <UID>0</UID>
  <GID>0</GID>
  <UNAME>oneadmin</UNAME>
  <GNAME>oneadmin</GNAME>
  <NAME>Alpine Linux 3.14</NAME>
  <PERMISSIONS>
    <OWNER_U>1</OWNER_U>
    <OWNER_M>1</OWNER_M>
    <OWNER_A>0</OWNER_A>
    <GROUP_U>0</GROUP_U>
    <GROUP_M>0</GROUP_M>
    <GROUP_A>0</GROUP_A>
    <OTHER_U>0</OTHER_U>
    <OTHER_M>0</OTHER_M>
    <OTHER_A>0</OTHER_A>
  </PERMISSIONS>
  <TYPE>0</TYPE>
  <DISK_TYPE>0</DISK_TYPE>
  <PERSISTENT>1</PERSISTENT>
  <REGTIME>1646067402</REGTIME>
  <SOURCE><![CDATA[one/12/0.vmdk]]></SOURCE>
  <PATH><![CDATA[https://marketplace.opennebula.io/appliance/6a810678-1771-43eb-aa03-2c5d7dabd980/download/0]]></PATH>
  <FORMAT><![CDATA[vmdk]]></FORMAT>
  <FS><![CDATA[]]></FS>
  <SIZE>256</SIZE>
  <STATE>1</STATE>
  <PREV_STATE>1</PREV_STATE>
  <RUNNING_VMS>0</RUNNING_VMS>
  <CLONING_OPS>0</CLONING_OPS>
  <CLONING_ID>-1</CLONING_ID>
  <TARGET_SNAPSHOT>-1</TARGET_SNAPSHOT>
  <DATASTORE_ID>100</DATASTORE_ID>
  <DATASTORE>nfs(IMG)</DATASTORE>
  <VMS/>
  <CLONES/>
  <APP_CLONES/>
  <TEMPLATE>
    <FROM_APP><![CDATA[336]]></FROM_APP>
    <FROM_APP_MD5><![CDATA[5ff0f4cd3bc864cf08b342367e8fe681]]></FROM_APP_MD5>
    <FROM_APP_NAME><![CDATA[Alpine Linux 3.14]]></FROM_APP_NAME>
  </TEMPLATE>
  <SNAPSHOTS>
    <ALLOW_ORPHANS><![CDATA[NO]]></ALLOW_ORPHANS>
    <CURRENT_BASE><![CDATA[-1]]></CURRENT_BASE>
    <NEXT_SNAPSHOT><![CDATA[0]]></NEXT_SNAPSHOT>
  </SNAPSHOTS>
</IMAGE>

CONTEXT = [
  NETWORK = "YES",
  SSH_PUBLIC_KEY = "$USER[SSH_PUBLIC_KEY]" ]
CPU = "1"
DESCRIPTION = "vCenter Template imported by OpenNebula from Cluster Cluster"
DISK = [
  IMAGE = "Alpine Linux 3.14",
  IMAGE_UNAME = "oneadmin" ]
GRAPHICS = [
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
HOT_RESIZE = [
  CPU_HOT_ADD_ENABLED = "NO",
  MEMORY_HOT_ADD_ENABLED = "NO" ]
HYPERVISOR = "vcenter"
INPUTS_ORDER = ""
LOGO = "images/logos/linux.png"
MEMORY = "256"
MEMORY_UNIT_COST = "MB"
NIC = [
  NETWORK_ID = "0",
  OPENNEBULA_MANAGED = "NO" ]
VCENTER_CCR_REF = "domain-c2001"
VCENTER_INSTANCE_ID = "9f82ad22-7beb-404e-9595-bf73e9c672bc"
VCENTER_TEMPLATE_NAME = "corelinux7_x86_64"
VCENTER_TEMPLATE_REF = "vm-3018"
VCENTER_VM_FOLDER = ""
VCPU = "1"
```

**Expected behavior**
It should deploy without errors.

**Details**
 - Affected Component: core
 - Hypervisor: vCenter
 - Version: 6.2.2 and development

**Additional context**

- The image is always downloaded as persistant.
- When terminating the VM, the images goes to ERROR state.

```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

vCenter 7.0

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Tested on Ubuntu 20.04 and it works without any error.

The problem in Ubuntu 18.04 is the qemu-img version, so we have added a note in the platform notes.

**Comment by tinova** [comment]
Note added on https://github.com/OpenNebula/docs/pull/2188
