### ISSUE TITLE
Importing a OneFlow template from marketplace into vCenter fails

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5812]
/!\ To report a **security issue** please follow this procedure:
   [https://github.com/OpenNebula/one/wiki/Vulnerability-Management-Process]

**Description**

If a VM Template is not selected, OpenNebula will try to create a new one. However, the signature of the function is different from the call:

```
App 2426 output: 2022-05-03 13:44:28 - ArgumentError - wrong number of arguments (given 2, expected 3..4):
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:315:in `create_vcenter_template'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:463:in `create_vm_template'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:269:in `block in export_vm_template'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:650:in `export_recursive'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:268:in `export_vm_template'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:80:in `export'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:626:in `block in export_recursive'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:608:in `each'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:608:in `export_recursive'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:294:in `export_service_template'
App 2426 output: 	/usr/lib/one/ruby/opennebula/marketplaceapp_ext.rb:82:in `export'
App 2426 output: 	/usr/lib/one/sunstone/models/OpenNebulaJSON/MarketPlaceAppJSON.rb:178:in `export'
App 2426 output: 	/usr/lib/one/sunstone/models/OpenNebulaJSON/MarketPlaceAppJSON.rb:54:in `perform_action'
```

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by al3xhh** [comment]
PRs to merge in 6.4 & master:

- [code](https://github.com/OpenNebula/one-ee/pull/2001)
- [docs](https://github.com/OpenNebula/docs/pull/2250)
