### ISSUE TITLE
Sunstone can't log in if public_fireedge_endpoint is declared and non functional

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6163]
**Description**
Sunstone can't log user in if `public_fireedge_endpoint` is enabled on `sunstone.conf`

**To Reproduce**
Start Sunstone with `public_fireedge_endpoint` enabled without FireEdge installed.

**Expected behavior**

**Details**
 - Version: 6.6

**Additional context**
Apache error log

```log
App 1808724 stderr: 2023-03-22 15:22:07 - NoMethodError - undefined method `downcase' for nil:NilClass:
App 1808724 stderr: /usr/lib/one/sunstone/views/index.erb:67:in `__tilt_1780'
App 1808724 stderr: /usr/share/one/gems-dist/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `evaluate'
App 1808724 stderr: /usr/share/one/gems-dist/gems/tilt-2.0.11/lib/tilt/template.rb:109:in `render'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:842:in `render'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:738:in `erb'
App 1808724 stderr: /usr/lib/one/sunstone/sunstone-server.rb:711:in `block in <top (required)>'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1691:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1691:in `block in compile!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1009:in `block (3 levels) in route!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1027:in `route_eval'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1009:in `block (2 levels) in route!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1058:in `block in process_route'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1056:in `catch'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1056:in `process_route'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1007:in `block in route!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1004:in `each'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1004:in `route!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1128:in `block in dispatch!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `catch'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `invoke'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1123:in `dispatch!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:939:in `block in call!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `catch'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `invoke'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:939:in `call!'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:928:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:261:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/deflater.rb:44:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-protection-3.0.4/lib/rack/protection/xss_header.rb:20:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-protection-3.0.4/lib/rack/protection/path_traversal.rb:18:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-protection-3.0.4/lib/rack/protection/json_csrf.rb:28:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-protection-3.0.4/lib/rack/protection/base.rb:53:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-protection-3.0.4/lib/rack/protection/base.rb:53:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-protection-3.0.4/lib/rack/protection/frame_options.rb:33:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/null_logger.rb:11:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:219:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:2002:in `call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1561:in `block in call'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1777:in `synchronize'
App 1808724 stderr: /usr/share/one/gems-dist/gems/sinatra-3.0.4/lib/sinatra/base.rb:1561:in `call'
App 1808724 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 1808724 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
App 1808724 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 1808724 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 1808724 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

![image](https://user-images.githubusercontent.com/33811723/226967364-9c4ae2c0-91b9-4dde-b6ef-c17ba54ecd9a.png)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Related PRs:
- code: https://github.com/OpenNebula/one-ee/pull/2567
- docs: https://github.com/OpenNebula/docs/pull/2534
