### ISSUE TITLE
Sunstone server crashes on login with remote auth enabled

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#6339]
**Description**
When configured with `:auth: remote` after the external authorization, clicking on the `Login` button, a server error is generated, and Sunstone is not loading data.

**To Reproduce**
Configure Sunstone to work with remote authentication behind a proxy, for example, OpenID Connector 
Open the URL
After successful authentication, a "login" page is shown
Click the Login button
A warning is displayed that there is an internal server error.

**Expected behavior**
After clicking the login button, the Sunstone should load the dashboard

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [6.4-ee, probably all versions affected]

**Additional context**
The same behaviour is observed with nginx or appace+passenger configured as a reverse proxy before Sunstone.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment]
Hello @atodorov-storpool! Currently looking into this and just wanted to clarify, does the actual Sunstone server crash when you try to log in or does the login request simply fail but the Sunstone server stays up and running?

**Comment by atodorov-storpool** [comment]
Hello @vichansson 
Just the process/thread is crashing. The sunstone is still working.

**Comment by atodorov-storpool** [comment]
log
```
Nov 07 12:11:15 a8one opennebula-sunstone[56252]: 2023-11-07 12:11:15 - NoMethodError - undefined method `match' for nil:NilClass:
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/lib/one/sunstone/sunstone-server.rb:567:in `build_session'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/lib/one/sunstone/sunstone-server.rb:851:in `block in <main>'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:255:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-protection-2.2.0/lib/rack/protection/xss_header.rb:18:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-protection-2.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-protection-2.2.0/lib/rack/protection/json_csrf.rb:26:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-protection-2.2.0/lib/rack/protection/frame_options.rb:31:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:50:in `block in process'
Nov 07 12:11:15 a8one opennebula-sunstone[56252]:         /usr/share/one/gems-dist/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by atodorov-storpool** [comment]
It looks like backporting commit https://github.com/OpenNebula/one/commit/9976d68487ec25dfcc789b8c232a357f7443741e to 6.4.4-LTS resolves the issue.

**Comment by tinova** [comment]
Thanks for the excellent feedback @atodorov-storpool !! We'll include this in the next 6.4 LTS release

**Comment by tinova** [comment]
Docs: https://github.com/OpenNebula/docs/commit/b8b11d51293061aa194716ac7085901a0650e97b
